### ISSUE TITLE
PPU - BGT being displayed at wrong point in chart

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1008]
On the PPU Chart [below](https://openprescribing.net/practice/F83032/0601060D0AAA0A0/price_per_unit/?date=2018-06-01) the item on the far right hand side (GlucoRx) should be located towards the left as it has a lower PPU (not the highest). The labels on the x-axis underneath it seemed to have changed to numbers, which Seb thinks is the issue

![image](https://user-images.githubusercontent.com/40460354/44717068-f6209b00-aab3-11e8-99b9-a5194d434253.png)

**Comment by evansd** [comment]
I haven't discovered the source of the numeric labels yet, but after discussing with Rich the underlying issue here is dodgy source data. There are two entries for "GlucoRx Nexus (Reagent)_Strips, one with only 52 items but a PPU of 0.57 (the small red dot in the top right) which drags up the mean PPU for that presentation:
```
 processing_date | pct_id | practice_id | quantity |        ppu        
-----------------+--------+-------------+----------+-------------------
 2018-06-01      | 01E    | P81179      |       52 | 0.574038461538461
```

According to Rich's research, these 52 items are composed of 50 normally price items, plus two items which have been paid out as two packs, giving a massively inflated PPU.

So the issue here seems to be the data rather than the chart, and needs a wider discussion on how to proceed. (Possibly connected to issue #2).

**Comment by evansd** [comment]
The issue with the numeric labels is just that the chart gets automatically expanded to fit the bubbles which means that the x-axis extends beyond the number of category labels we have supplied for it. So Highcharts fills in with numeric labels. We can work around this by supplying our own list of labels which we pad with empty string values.
