### ISSUE TITLE
Anomaly in Quetiapine Measure

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1031]
The text says the CCG is prescribing better than the median - if you look on graph though it is prescribing worse than the median.

![image](https://user-images.githubusercontent.com/40460354/45085830-8f296480-b0f9-11e8-927d-4e43d08d91e5.png)

The measure is [here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/quetiapine.json)

I think the anomaly is being driven by high proportion of branded generics.

**Comment by richiecroker** [comment]
It could be due to the disparity in price between when the measure was created and now, due to the huge NCSO hike of standard-release and the slow reduction since.  

We have a choice in what to do with this measure:

- Withdraw/retire it (based on the fact that the cost savings are no longer there), and possibly resurrect if it becomes cheap again
- Make it a non-cost saving measure

My view would be to retire it for now - there's no real clinical benefit to giving more tablets a day, but when the price difference was 50 fold, it did make sense.  Thoughts @brianmackenna ?

**Comment by brianmackenna** [comment]
As discussed - agree withdraw.

We should keep it on hand to resurrect, as the price seems to be [correcting](https://openprescribing.net/tariff/?codes=0402010ABAABABA&codes=0402010ABAAAFAF) 

Our mental health dashboard will only have two measures, will need to keep a look out for good measures.

**Comment by HelenCEBM** [comment]
Measure retired
