### ISSUE TITLE
Non-unique practice names causing issue on Analyse page

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1119]
Here are a couple of examples (as spotted by @richiecroker):
https://openprescribing.net/analyse/#org=practice&orgIds=99P,99Q&numIds=21480000100&denom=total_list_size&selectedTab=summary
https://openprescribing.net/analyse/#org=practice&orgIds=99P,99Q&numIds=0212000B0&denom=total_list_size&selectedTab=summary

![openprescribing net_analyse_](https://user-images.githubusercontent.com/19630/47009530-a6199880-d134-11e8-9940-f0ebd8b8c77c.png)

The issue is caused, I assume, by the fact that practice names are not unique but Highcharts (as we currently have it configured) assumes that category labels *are* unique.

I remember seeing somewhere in the Highcharts release notes that it now supports non-unique category  names via some kind of config setting so we should look into that.

**Comment by evansd** [comment]
Small update:
Just setting [uniqueNames](https://api.highcharts.com/highcharts/xAxis.uniqueNames) to `false` on the xAxis configuration does solve the problem on initial load, but then it breaks the chart badly if you move the time-slider.

**Comment by HelenCEBM** [comment]
Can we merge all practice names with their practice code? I.e. so they appear as 
"Collingwood surgery, A87004"? 

This would probably help some users distinguish between practices as well, and allow searching by code e.g. in practice search page - e.g. here the names are similar and some postcodes are also similar:
![image](https://user-images.githubusercontent.com/24392156/48189986-60b64880-e339-11e8-9fb2-123a75c12f83.png)

We recently had a user ask how to tell which practice he was looking at since they shared both name and address. 

It wouldn't make a difference to the appearance of analyse search results because in the image @evansd  posted above, the names are truncated anyway.

**Comment by evansd** [comment]
Oh that's a nice suggestion. I think we should definitely try that on the Analyse page as hopefully it will fix that problem with very little work.

I don't think we should merge them everywhere as it's useful to be able to control where and how the codes appear, but it would probably make sense to display them in the list of practices (and somewhere on the dashboard itself, if we don't already).

**Comment by HelenCEBM** [comment]
A user has raised a query relating to an alert for this analysis: https://openprescribing.net/analyse/#org=practice&orgIds=E87742&numIds=6.1.2&denom=total_list_size&selectedTab=summary

> There are 2 surgeries with a similar name
> The Golborne Medical Centre
> Mine is E87742, on the data it is now showing as the other surgery!

![image](https://user-images.githubusercontent.com/24392156/50341324-4d8cc000-0516-11e9-8d69-3a5882e04d0c.png)

**Comment by sebbacon** [comment]
Just a reminder for future us to check out #1368 when we fix this
