### ISSUE TITLE
Several measures don't allow you to break down into individual presentations

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1203]
This was raised by attendees at my talk in Wakelfield who were trying to explore their hypnotics prescribing

Their [dashboard](https://openprescribing.net/ccg/03R/measures/)
![image](https://user-images.githubusercontent.com/40460354/48675414-7a813800-eb50-11e8-86be-23bd40d3b365.png)
 
And the measures

- https://openprescribing.net/ccg/03R/bdzper1000/
https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/bdzadq.json
- https://openprescribing.net/ccg/03R/bdzadq/
 https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_definitions/bdzadq.json

**Comment by inglesp** [comment]
This affects the following measures:

* bdzadq
* bdzper1000
* ktt9_uti_antibiotics
* lpneedles
* lpzomnibus
* opioidome
* pregabalinmg
* test_strip

This is because the numerators for these measures involve more than aggregating over `hscic.normalised_prescribing_standard`.

There are two classes:

1. numerators that aggregate over a view in BQ
    * lpzomnibus (aggregates `practice_data_all_low_priority`)
    * opioidome (aggregates `opioid_total_ome`)
    * pregabalinmg (aggregates `pregabalin_total_mg`)
2. numerators that aggregate over `hscic.normalised_prescribing_standard` and `JOIN` on another table
    * all the others

In case 2, we can work out which presentations contribute to the numerator with something like:

`SELECT DISTINCT bnf_code FROM {measure.numerator_from} WHERE {measure.numerator_where}`

This is not possible in case 1, as the BQ views do not have `bnf_code` columns.  For these cases, we will have to find another way to work out which presentations contribute to the numerator.  We can either hardcode this (not ideal) or add a field to `Measure` that contains enough SQL to generate the list.

In both cases, we will want to add a `numerator_bnf_codes` column to the `Measure` table, probably an array, which we can then use to generate the list of presentations in `measure_numerators_by_org`.  We may as well do this for measures whose numerator is already queryable, as that should simplify the implementation.

**Comment by sebbacon** [comment]
Sounds good. Could we alter the views in case (1) so they also return a `bnf_code` column?

**Comment by inglesp** [comment]
> Could we alter the views in case (1) so they also return a `bnf_code` column?

No, since each row already aggregated to practice level.

**Comment by sebbacon** [comment]
Sorry if this isn't a helpful query (I'm in a hurry!) but doesn't the measure infrastructure group by practice anyway, in which case isn't the aggregation in the views an optimisation which can potentially be bypassed?

**Comment by inglesp** [comment]
> ...isn't the aggregation in the views an optimisation which can potentially be bypassed?

Don't think so, but may be misunderstanding.

Consider the opioidome measure.  This has numerator roughly `SUM(total_ome) AS numerator FROM measures.opioid_total_ome`.

And `measures.opioid_total_ome` is a view with SQL:

```
SELECT
  month,
  practice,
  pct,
  SUM(quantity*dose_per_unit*ome_multiplier) AS total_ome
FROM
  ebmdatalab.hscic.normalised_prescribing_standard AS presc
JOIN
  -- data in richard.opioid_measure comes from:
  -- https://docs.google.com/spreadsheets/d/1IjnHbYVszZKPmVSYydtMVzbDLPOmq8bOFq45QsSu6sE/edit?usp=sharing
  ebmdatalab.richard.opioid_measure as opioid
ON
  CONCAT(SUBSTR(presc.bnf_code,0,9),'AA%',(SUBSTR(presc.bnf_code,-2,2)))=CONCAT(SUBSTR(opioid.bnf_code,0,11),'%',(SUBSTR(opioid.bnf_code,-2,2)))
GROUP BY
  month,
  pct,
  practice
```

There's a `bnf_code` column `ebmdatalab.richard.opioid_measure`, but `import_measures` has no way of getting access to that.

But we should be able to add a field to this measure that like `m.numerator_bnf_code_query = 'SELECT DISTINCT bnf_code FROM ebmdatalab.richard.opioid_measure'`.  And we can do similarly for the other measures in case 1.
