### ISSUE TITLE
Error Code 500: Email SignUp for an Individual User

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1303]
We received the following email

> New feedback from xxxxxxxxxxx@nhs.net) via https://openprescribing.net/practice/M85008/ Can&#39;t subscribe on you Web page -please add me to you mailing list for newsletter and  alerts

I tried signing the email up but the website returned an  Error Code 500 message

![image](https://user-images.githubusercontent.com/40460354/50677549-4e335500-0ff2-11e9-8530-16666bd10309.png)

I then signed up using my own email address to that alert so not sure why the user email triggered the error.

**Comment by inglesp** [comment]
There are two `OrgBookmark`s for the practice in question with the same user, created a fraction of a second apart!

```
>>> [ob.created_at for ob in OrgBookmark.objects.filter(practice_id='M85008', user_id=3012)]
[datetime.datetime(2018, 12, 30, 6, 47, 50, 495384, tzinfo=<UTC>), datetime.datetime(2018, 12, 30, 6, 47, 50, 494770, tzinfo=<UTC>)]
```

I guess this is a race condition, with the user somehow submitting three requests in rapid succession, with the first two in parallel, handled by separate processes and succeeding, and the third happening shortly afterwards and failing.

**Comment by inglesp** [comment]
I will delete one of the `OrgBookmark`s, and then all should be right with the world.

**Comment by inglesp** [comment]
However!  There are lots of other dodgy `OrgBookmark`s...

<details>
<summary>Here's a full list</summary>

```
>>> c = Counter((ob.user_id, ob.practice_id) for ob in OrgBookmark.objects.filter(practice_id__isnull=False))
>>> for (user_id, practice_code), count in c.most_common():
...   if count > 1:
...     print count, user_id, practice_code
... 
4 480 B83054
4 180 M85108
3 584 B86044
3 491 L85009
3 1281 L83070
3 2783 N81087
3 630 C88051
3 1194 K82008
2 994 M86030
2 1601 L84616
2 431 F86040
2 70 M85019
2 598 L81637
2 76 Y05167
2 2825 C88048
2 2848 F81021
2 447 B86051
2 1263 B83055
2 598 L81065
2 2034 E85029
2 1355 C81008
2 630 C88036
2 630 C88020
2 2563 A83006
2 630 C88073
2 1047 L83038
2 133 B82023
2 753 F81649
2 1144 K84026
2 1047 L83608
2 1201 C88019
2 2411 D83056
2 2656 P87024
2 1111 J83035
2 1169 K83625
2 2401 L81051
2 2652 A81066
```

</details>

And while I don't see any others with timestamps so close together, there are some that have been created recently, which suggests that it is possible for a user to create a duplicate `OrgBookmark`.

@sebbacon Do you think this is worth investigating further?

**Comment by sebbacon** [comment]
It looks like the bug might arise in L1135?

https://github.com/ebmdatalab/openprescribing/blob/66097603cb29df82a06891175381170508a07d6d/openprescribing/frontend/views/views.py#L1131-L1138

The intent there is explained here:

https://github.com/ebmdatalab/openprescribing/blob/66097603cb29df82a06891175381170508a07d6d/openprescribing/frontend/views/views.py#L1011-L1018

In other words, it's part of preventing people from signing up other users to things they didn't want to be signed up to. We agreed in #1048 to remove double opt-in, so longer term we shouldn't have to worry about this.

I guess the "race condition" is that someone has successfully signed up and confirmed their email; but caching (or something like that) means they weren't logged in (or thought they weren't); then they tried to subscribe again when not logged in... roughly speaking.

I think the fix is not to `get_or_create` using the `approved` key, but to set that value on the retrieved object?

I think we should fix this if it's not too much hassle, although there is an underlying issue with something to do with caching or similar which I recall looking at together last year? And this *will* go away with #1048
