### ISSUE TITLE
tariff import error

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1420]
`dmd.models.DoesNotExist: DMDVmpp matching query does not exist.`

See https://sentry.io/ebm-datalab/openprescribing/issues/863277086/

Also, when exception is raised, we get `No handlers could be found for logger "dmd.management.commands.fetch_and_import_drug_tariff"`

**Comment by inglesp** [comment]
See https://github.com/ebmdatalab/openprescribing/issues/1126.

**Comment by inglesp** [comment]
Imports were still failing after #1126 was fixed we began importing dm+d data again.

The DT referenced a VMPP that wasn't in our dm+d data, because we import dm+d monthly but it's released weekly.

I manually imported the latest dm+d data then and reran the DT importer successfully.

There's a longstanding issue (#956) about importing dm+d data weekly.  This should be done as part of the work for the new dm+d browser.
