### ISSUE TITLE
Review non-CCG NCSO analysis

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1477]
[This](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/price_concessions/NCSO%20Workbook.ipynb) is @brianmackenna's first entirely-self-authored notebook (I believe!)

Do a brief review for
a) logic
b) style

Really this is mainly a sanity-check - style stuff requires a larger conversation (e.g. WRT [the new library](https://github.com/ebmdatalab/datalab-pandas))

He may also need help getting his github app running. I solved this with Rich - the question marks in file names thing did fix it, but rich had to delete and reclone before things worked.

**Comment by inglesp** [comment]
Feedback:

The Big Hairy SQL at the top is big and hairy!  It could do with a comment explaining what it’s retrieving.

The SQL doesn’t make any adjustments for a discount factor, and nor does it account for 0206010F0AACJCJ where “quantity” apparently means “number of packs”.  @dave’s SQL (at the practice level) does account for these.

The two subqueries are quite similar, with three differences:

* The first has a `FULL OUTER JOIN` on `hscic.ccgs` while the second has `JOIN` (which is an inner join).  I don’t think this is deliberate, but if it is, it should be commented.
* The second includes `WHERE ncso.date > (SELECT MAX(rx1.month) FROM hscic.normalised_prescribing_standard_latest_month AS rx1)`.  Since `normalised_prescribing_standard_latest_month` is a view that queries `normalised_prescribing_standard`, you should query that directly, with ``WHERE ncso.date > (SELECT MAX(rx1.month) FROM hscic.normalised_prescribing_standard AS rx1)`/
* The first has `month` in its output columns, while the second has `ncso.date`.  Since the first query includes `rx.month = ncso.date` in a `JOIN` conditions, you should be able to change `month` to `ncso.date` without affecting the results.  This would make the two subqueries more similar, and would highlight the significant differences.

There are also some cosmetic changes I think you should make:

* Ensure consistent indents
* Don’t bother with the backticks around table names
* Put single spaces around comparison tokens (eg `this = that`, not `this=that`)

As far as I can tell, the rest of the Pandas code is fine and does what you want it to.

Before publishing, you should:

* Add brief narrative to explain what you’re computing, eg: “Here we’re computing the total cost to all non-CCG organisations in 2018”, (although you’ve gone for good descriptive variable names)
* Re-run the notebook from scratch (“Restart and run all” in the kernel menu) to make sure that anybody else can run it (although: can they?  our BQ data isn’t public, so what’s your expectation here?)
* Work out how to share the CSV files (if you expect somebody else to be able to run the code)
* Consider truncating many/all of the large DataFrames -- you can include the data in tables linked to from the blog, but to me the notebook should be about how to do the calculations, and shouldn’t include the results

I’d be very happy to review again before publication.  (And I look forward to your feedback on my titration skills.)

**Comment by brianmackenna** [comment]
Thanks for the feedback @inglesp . I have actually made two new versions.

[Version one](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/nonCCG%20concessions/nonCCG%20Concessions.ipynb): This is developed based on feedback from yourself and a little discussions with @rich about the joins. There are differences on the join but I couldn't figure out exactly what the differences are.

[Version two](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/nonCCG%20concessions/OP%20SQL%20nonCCG%20Concessions.ipynb): I have written this one using @evansd  SQL (available [here](https://gist.github.com/evansd/cea797a322c98b6352b58cc8772f26ee)) I have done this to keep consistent with site SQL but it is very similar figures to version 1.

My intention is to write a blog (draft will be available [here](https://docs.google.com/document/d/1eKOf8OtP3FGpM5ukOt18gPJxN8W85iVoXFtLm1FHgII/edit?usp=sharing)) and I will use version 2 for the figures. I will also point to it in the blog as demonstration of open analysis and also clinicans picking up new skills by learning from our.

**Comment by inglesp** [comment]
Do you want me to review the new notebooks?

**Comment by brianmackenna** [comment]
Yes please. 
In the interests of time version 2 should be prioritised over version 1 as that is what I'll point to in the blog.

**Comment by inglesp** [comment]
Have reviewed number two.  Looks good, well done!

I've not reviewed the SQL in detail -- I'm assuming it's identical to what Dave provided.

You say "getting multiple errors when trying to drop all at once" -- have you tried `purchaser_list = fullmerge.drop(['name_council', 'name', 'name_independent_provider')], axis=1)`?  Also, do you need to drop these, as at the end you're only showing `purchaser_list2[['purchaser_name', 'pct', 'additional_cost']]`.

I'd suggest making a few structural changes:

* **Introduction.**  "This notebook calculates...  It shows that the most-affected non-CCG is..."
* **Housekeeping.**  Set options.  Do imports.  Set project ID.
* **Load data.** Load all data in one section.  Give one line describing what each data contains, and use `.head()` to show the first five rows.
* **Massage data.** Do the filtering, sorting, index-changing, merging, calculating, etc.
* **Present results.** By this point you should have a set of DataFrames that contain the results you need.

You might find that it makes sense to mix a bit of calculating in with presenting the results, but I don't think that's going to be necessary here.

I'd also make some changes to the names of your variables.

* There's no need to include `df` in the name of variables pointing to DataFrames.  (eg `df_councils` could just be `councils`.)
* A name like `importmerge_orgnames_part1`, `fullmerge` doesn't tell me the variable actually points to.
* In your data munging, you're creating a bunch of temporary DataFrames.  You might be able to get away with having a single variable (eg `spending_by_org`), and then updating it:

```
spending_by_org = pd.read_gbq(q, GBQ_PROJECT_ID, dialect = 'standard')
spending_by_org = spending_by_org[spending_by_org.org_type !='CCG']
spending_by_org = spending_by_org.loc[(spending_by_org["month"]>="2018-01-01") & (spending_by_org["month"]<="2018-12-01")]
... etc ...
```

Some functions have an `inplace=True` argument which might help here.

In fact, if you only ever have a single variable pointing to a DataFrame, it would be acceptable (in my view) to call it `df`.

Hope this is helpful!  If you wanted to send me CSV files, I could have a go at updating the notebook myself.

**Comment by brianmackenna** [comment]
Thanks @inglesp  really thorough and helpful. 

SQL: It isn't identical. @evansd  [SQL](https://gist.github.com/evansd/cea797a322c98b6352b58cc8772f26ee) uses practice and pct while in mine I had to bring in "organisation type" from `hscic.ccgs` to identify nonCCGs. As the value is similar to prototype SQL from @richiecroker I think I did it correctly.

csv files: I created a new folder in Jupyter notebooks folder and actually the csv files are there as well. See [here](https://github.com/ebmdatalab/jupyter-notebooks/tree/master/nonCCG%20concessions).

Structural changes: Good pointers. Basically the structure is the way I worked through the problem first time round. For example I didn't know I would need the other ODS csv files for names until I got to it.

Merging and dropping: This was my first real go at merging and dropping so bit of trial and error and a lot from StackOverflow which got me to where I needed to be, but as you point out is not the best way.

**Comment by brianmackenna** [comment]
Updated notebook is in Jupyter notebooks bucket [here](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/nonCCG%20concessions/OP%20SQL%20nonCCG%20Concessions.ipynb) , the [folder](https://github.com/ebmdatalab/jupyter-notebooks/tree/master/nonCCG%20concessions) has associated csv and the first attempt before feedback for transparency.

My draft blog on subject is[ here](https://docs.google.com/document/d/1eKOf8OtP3FGpM5ukOt18gPJxN8W85iVoXFtLm1FHgII/edit?usp=sharing)
