### ISSUE TITLE
Build the alert signup flow

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing#151]
Build the "sign up for alerts" front end. This involves:
- Sign up for emails from an organisation dashboard, or from the analyse page
- Unsubscribe from a particular email alert (or all email alerts)

Here is the mockup we tested successfully, we can replicate this design as closely as possible I think:

https://marvelapp.com/2a1e7b7

We'll also need the equivalent on the /analyse page - we may want to experiment with that going above or below the chart.

**Comment by annapowellsmith** [comment]
This is the sketch I have for when the user clicks the "unsubscribe all" link: https://goo.gl/photos/9RzZVcE2A23jxGi18

**Comment by sebbacon** [comment]
Progress update:

* I've got a nice workflow going on my laptop for signing up for CCG emails, which I wanted to show, so I deployed it; but it doesn't work there because of some stupid CORS / HTTPS issue that I've not grappled with yet.
* This covers signing up, unsubscribing, etc. The workflow was (predictably?!) more complicated than expected, e.g. what should happen if you've already confirmed your email address, etc.
* Still to do
  * Clean up the unsubscribe page design
  * Add "unsubscribe from all" functionality
  * Add the same functionality to practices 
  * Write tests, review code, turn into sane commits

As discussed, I'm leaving the analyse workflow until we've had more discussions.

**Comment by sebbacon** [comment]
Can't deploy to staging because of pathological postgres performance which is blocking a migration from running (see #157). Will look at postgres issues on Monday by when I'm hoping the current matviews generation will have finished.

**Comment by sebbacon** [comment]
All done, bar refactoring and adding tests. Will hopefully deploy to staging on Monday (postgres permitting)

**Comment by sebbacon** [comment]
@annapowellsmith, this is now deployed to staging. You can sign up on ccg and practice pages. The URL for unsubscribing is https://staging.openprescribing.net/bookmarks/. There's a version with a secret key on the end that gets sent in emails, but the version without the key will work until you close your browser so should be good enough for testing.

**Comment by annapowellsmith** [comment]
Looks great!

Design thoughts (haven't looked at code):

- I think the input field would be better positioned next to the sort buttons, as per Henry's mockup (and on mobile should go directly above them) 
- Input field needs to be wider 
- The confirm page should have a link saying "back to previous page", so you don't have to click the back button (ideally I guess we'd do it in an Ajaxy way, is that tons of extra work?)
- The practice and CCG signup pages are styled differently
- The "From" address on the signup shouldn't be openprescribing.errors
- We need a signup on the analyse page too
- "monthly" not "monthy" :) (actually I want to change that message slightly, I'll have a think)
- And finally I reckon we should have an exclamation mark after the "Thanks" message on the confirmation page!

**Comment by sebbacon** [comment]
Great, thanks for the feedback. I like your perky exclamation mark style! (Though I bet some people would want to kill us over it).

Some responses to some specific points:

> I think the input field would be better positioned next to the sort buttons, as per Henry's mockup (and on mobile should go directly above them)

I deliberately departed from the mockup because I remembered literally no-one noticed it when we tested it (though I wasn't present for all the testing). I took that as a sign it was in the wrong place, but perhaps it was in the right place but needed some other visual signposting?

> The practice and CCG signup pages are styled differently, though I guess this will change anyway

How? I see there is an extra `<hr>` on the practice version; anything else?

> We need a signup on the analyse page too

Deliberately left out because I wasn't sure we had decided on the copy for emails, and hadn't tested the flow (which would be slightly different as we thought people would probably want to give their analyse bookmarks a custom name, etc).  Can we add the analyse alerts in as the next release, pending further discussions and possibly testing?

**Comment by annapowellsmith** [comment]
> I deliberately departed from the mockup because I remembered literally no-one noticed it when we tested it (though I wasn't present for all the testing). I took that as a sign it was in the wrong place, but perhaps it was in the right place but needed some other visual signposting?

My sense is that it's in the right place logically, because it's a feature, separate from intro text. However it may need more visual signposting and better copy - but we can refine those. 

> How? I see there is an extra `<hr>` on the practice version; anything else?

That's the one.

> Deliberately left out because I wasn't sure we had decided on the copy for emails, and hadn't tested the flow (which would be slightly different as we thought people would probably want to give their analyse bookmarks a custom name, etc).  Can we add the analyse alerts in as the next release, pending further discussions and possibly testing?

We did test this a bit, I guess after you had left, and it tested OK. There's an email in the drive, look for "Testing email for custom measure". However, if you prefer to add it in next release and focus on this for now, that's fine with me.

**Comment by sebbacon** [comment]
Also N.B. 

* Anna got a CSRF error at some point when submitting an email address - check logs
* Maybe remove user profile URL routing for the time being

**Comment by sebbacon** [comment]
Draft minimal spec here https://docs.google.com/document/d/1AmOV4W5t0jRKnOWBEU7F6Gbz9IEIiJailZIhGct-mc4/edit

Needs a bit more work, specifically things it won't include, and things it would be nice to include if we have time.
