### ISSUE TITLE
Format all code with black

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1669]
We've agreed that we'll format all code with [`black`](https://github.com/ambv/black).

Here's a suggested pathway:

- [x] Ensure all code can be formatted by `black`.  This means removing any Python 2 constructs.  See #1668.
- [ ] Merge all open PRs.
- [ ] Run `black` over the whole codebase, and create a single commit with the diff.
- [ ] Set up a pre-commit hook to run `black --check` on any changed files.  This might be different on each developer's machine, as we likely all have virtualenvs set up differently, and since `black` only runs on Python 3, it'll need its own virtualenv.
- [ ] Run `black --check` against all new PRs.  We might be able to get codeclimate to do this, or we could use Travis.
- [ ] Redirect energy spent formatting code to something more productive.

@sebbacon @evansd input please!

**Comment by sebbacon** [comment]
For the emacs users in the team, there's a [minor-mode](https://github.com/proofit404/blacken/blob/master/blacken.el) that blackens files on saving, which said users might consider using instead of a git hook.

Per conversation elsewhere, seems sensible to set it up as a Travis test rather than codeclimate (which we still want to complain about Javascript and CSS...)

**Comment by evansd** [comment]
Closed by #1955
