### ISSUE TITLE
Clarify current `calc_value` implementation

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#175]
The [current logic](https://github.com/ebmdatalab/openprescribing/blob/6a3b49af4595e225c920ed2dba7cc1cfe21c6a4a/openprescribing/frontend/management/commands/import_measures.py#L433-L441) implies:

| numerator | denominator | ratio |
|---------------|-------------------|-------|
| 1                | null               | null  |
| 1                | 0                   | null  |
| 0                | null               | null  |
| null             | 1                  | null  |
| 0                | 1                   | 0      |
| null             | null               | null  |
| 1                | 2                   | 0.5   |

I'm not clear:

* Why we sometimes return null rather than 0 -- doesn't missing prescribing data *mean* zero items prescribed?
* In particular why the 1st example isn't 1, and the 4th example isn't 0

UPDATE: I've just noticed that we [set all falsey numerators to zero](https://github.com/ebmdatalab/openprescribing/blob/6a3b49af4595e225c920ed2dba7cc1cfe21c6a4a/openprescribing/frontend/management/commands/import_measures.py#L260) (and denominators), which changes the logic of the `get calc_values` function to:

| numerator | denominator | ratio |
|---------------|-------------------|-------|
| 1                | 0                   | null  |
| 0                | 0                   | 0      |
| 0                | 1                   | 0      |
| 1                | 2                   | 0.5   |

This now makes more sense, but I might have expected the ratio for the 1st line to be 1?

**Comment by annapowellsmith** [comment]
As discussed [what `get_calc_values` returns](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_measures.py#L433L441) is:

| numerator | denominator | ratio |
|---------------|-------------------|-------|
| 1                | 0                   | null  |
| 0                | 0                   | null      |
| 0                | 1                   | 0      |
| 1                | 2                   | 0.5   |

We set null numerator and denominator values to 0 because that is what they are, logically: no results = zero prescribing. (Note that `get_calc_values` assumes this has already happened.)

If the numerator is 0 and the denominator is 1 then we return null because we are always working with proportions, not ratios: so logically that scenario is impossible.

All good?

**Comment by sebbacon** [comment]
All good.
