### ISSUE TITLE
High Cost Statins measure not working

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#176]
Something is strange...

https://openprescribing.net/ccg/04L/statins/

**Comment by sebbacon** [comment]
I *think* this is because we (temporarily) deleted some measures pending updates, because the cost-saving algorithm was wrong. Unfortunately, I can't find a reference to that so I'd just like @annapowellsmith  to confirm.

Since then we've been updating data since April (issue #148) (which is *still* running due to database issues which I hope would be fixed by #165), and a single month's worth of data has therefore been generated for that measure.

Need to discuss with @annapowellsmith what the best next step is. I think we need to:

* Re-delete the measures that were previously deleted, pending:
* I'm currently half way through #165 which should radically speed up measures calculations - focus on finishing that

**Comment by annapowellsmith** [comment]
Thanks for reporting @lmfrench 👍 

This error occurred because I decided to delete the "bucket" measures (i.e. the ones based on long lists of individual codes rather than a single chemical) - statins, ace, arb, ppi - from the production database, but I forgot to remove them from the JSON definitions file, so they got re-created in the latest import. Oops!

I decided to delete these because they are typically the measures with low numbers for practices (except statins), and the charts with low numbers tested badly. Richard Croker suggested we should delete these, and I agree. 

Also, I think they are less intuitive than measures based on one or two chemicals, because the change we're suggesting people make is less obvious (they have to click through to the list of high-cost codes, then remember not to prescribe those codes). 

I think we should still have statin/ACE/ARB/PPI measures, but we should try to come up with a simpler definition, and we should also fix the issues around displaying low numbers first. 

@sebbacon will put in a PR to handle the exception in the JavaScript code, and I will put one in to remove these measures from the definitions file, and I will also delete the re-calculated measures from the production database (checking that this doesn't interfere with any running SQL).
