### ISSUE TITLE
Analyse Page Totals don't match at different org levels

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1768]
On the Analyse page (which is so so so handy in my role) the totals do not match up when you total at a different organisational level. See Atorvastatin national example

- https://openprescribing.net/analyse/#org=CCG&numIds=0212000B0&denom=nothing&selectedTab=summary totalled at CCG level
- https://openprescribing.net/analyse/#org=stp&numIds=0212000B0&denom=nothing&selectedTab=summary totalled at STP level
- https://openprescribing.net/analyse/#org=regional_team&numIds=0212000B0&denom=nothing&selectedTab=summary totalled at regional level

**Comment by inglesp** [comment]
Summary:

* The two new CCGs do not have STPs, which accounts for most of the difference
* The CCG total only includes prescribing from CCGs, while the RT total also includes prescribing from commissioning hubs

**Comment by inglesp** [comment]
Notes:

The April 2019 total spending is shown as:

* £4,196,634 for all CCGs
* £4,036,882 for all STPs
* £4,196,636 for all RTs

The difference between CCGs and RTs is minimal.

The cause is that `_practice_to_ccg_map`/`_practice_to_stp_map`/`_practice_to_regional_team_map` return slightly different sets of practices.

```
>>> Practice.objects.filter(ccg__org_type='CCG').count()  # _practice_to_ccg_map
10940
>>> Practice.objects.filter(ccg__stp_id__isnull=False).count()  _practice_to_stp_map
10592
>>> Practice.objects.filter(ccg__regional_team_id__isnull=False).count()  # _practice_to_regional_team_map
11285
```

Since these computations are all related to properties of a practice's CCG, we can look at those instead:

```
>>> PCT.objects.filter(org_type='CCG').count()
221
>>> PCT.objects.filter(stp_id__isnull=False).count()
195
>>> PCT.objects.filter(regional_team_id__isnull=False).count()
245
```

And here's a Venn diagram:

![image](https://user-images.githubusercontent.com/28734/59951213-1325c080-9470-11e9-992d-220c1e8639ee.png)

* There are 6 CCGs that are not in an STP or an RT
  * These are all closed
    * Only 1 (01M, NHS CENTRAL MANCHESTER CCG) has any associated practices
      * These are both closed with setting 0
      * They have no prescribing associated with them
* There are 20 CCGs that are in an RT but not in an STP
  * 18 closed at the end of March
    * All associated practices are closed with setting 0
      * There is no associated prescribing for Atorvastatin
      * There is a handful of prescribing for other stuff
  * 2 (15M, NHS DERBY AND DERBYSHIRE CCG; 15N NHS DEVON CCG) opened at the start of April
    * **This would probably account for the bulk of the difference total prescribing for CCGs and STPs**
* There are 30 non-CCG PCTS, and all of these are not in STPs
  * They are all commissioning hubs
    * Several have associated practices with some prescribing of Atorvastatin
    * These are mostly setting 25 (prisons) with a secure training centre and a secure children's home
    * **This would probably account for the small difference between total prescribing for CCGs and RTs**

**Comment by inglesp** [comment]
Next steps:

* @inglesp to track down latest STP membership
* @evansd to lead decision about whether to include non-CCGs in RT analysis
