### ISSUE TITLE
Odd PPUs evident at all-England level

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1832]
## "Backwards GBG"
A few products (e.g. [Isosorbide mononitrate](https://openprescribing.net/all-england/0206010K0AAAEAE/price-per-unit/?date=2019-04-01)) show generics consistently at lower prices. [Diltiazem](https://openprescribing.net/all-england/0206020C0AAAAAA/price-per-unit/?date=2019-04-01), of course, should only be prescribed by brand

![image](https://user-images.githubusercontent.com/211271/61029145-480f9e00-a3b2-11e9-862d-3fb2788ff413.png)

![image](https://user-images.githubusercontent.com/211271/61029220-72615b80-a3b2-11e9-99a9-4ab048b77194.png)

## Two MRs for one branded generic
For [Metformin](https://openprescribing.net/all-england/0601022B0AAAVAV/price-per-unit/?date=2019-04-01), Actavis has a variable price depending on pack size and Metabet has a consistent price:

![image](https://user-images.githubusercontent.com/211271/61029290-a2a8fa00-a3b2-11e9-856d-50046b70d936.png)

We have emailed them about it

## GBG at odd levels

This might just be a standard GBG issue, but it is striking that there are roughly equal amounts of PPU for [Mesalazine](https://openprescribing.net/all-england/0105010B0AAAAAA/price-per-unit/?date=2019-04-01) at every price point between the cheapest and most expensive brands.
![image](https://user-images.githubusercontent.com/211271/61029378-cd934e00-a3b2-11e9-8412-02c564a94416.png)

**Comment by brianmackenna** [comment]
Diltiazem: A small pedant point but the BNF point around brand prescribing only pertains to >60mg. There are a lot of diltiazem generics. However the dmd does state _Caution - AMP level prescribing advised_ at the VMP level (see [here](https://openprescribing.net/dmd/vmp/319205001/))

Mesalazine: I think we have to assume it is GBG but the price spread is odd. As regards quantity, the circles don't look proportionate to me.

**Comment by sebbacon** [comment]
Metabet: The Actavis product has apparently not been available since 2014. So the deeper puzzle there is what is actually being dispensed when the Actavis product is prescribed? And then, why does *that* have such variable pricing?

**Comment by brianmackenna** [comment]
Metabet: I would assume the available Morningside preparation is being dispensed. The majority of people will not even realise the technical variation in a different MA holder. Also with only one available on their shelf, it is just the obvious to dispense.

Regarding the pricing I have had a response from NHS BSA to some confirmatory questions (in italics) I asked.

__I have a query about  Metabet SR_Tab 1000mg (Actavis) . The most recent prescribing is attached and I was wondering what explains the variation in the net ingredient cost?_ Only two prescriptions (highlighted in green) correspond to price in dm+d. I have highlighted other groups of clustering on a NIC to try and spot a pattern._

> No price is held on dm+d for the listing of Metabet (Actavis) discontinued product, therefore, the basis of reimbursement will be made as per the endorsed invoice price. This should explain the variations in the NIC.

Note on dm+d there is a price listed but this is the last price. There is another field `Price basis` which states there is "no price available"

_Separately, the dm+d indicates that this product has been unavailable since 2014. Is there any point at which the BSA will not reimburse unavailable products?_

 > The BSA will reimburse unavailable products provided sufficient information is supplied by the contractor.

Despite appearing illogical there may be occasions where an "unavailable" product is available for example a product is discontinued but pharmacy actually has a couple of months on their shelf. Allowing this in a blanket fashion though does not make sense for products discontinued 5 years ago, we will investigate further. 

_On a related note there is another identical product Metabet SR_Tab 1000mg (Morningside) with a different MA and BNF code. It does appear to be available and I’m assuming this is the physical product a patient gets._

> You are correct there is a current listing of Metabet SR_Tab 1000mg (Morningside) on dm+d. However, should the contractor be dispensing the Morningside product then this should be made clear on the prescription submitted for reimbursement.

This gets to price variation. So we assume Morningside product is being dispensed, that means we would expect the Morningside dm+d price to be paid. Why might this be happening? My theory is the pharmacy contractor is endorsing the price on the invoice. This may or may not relate to dm+d, for example
- they may have received a discount and endorsed the net cost less discount
- they may have mixed up price of product unintentionally 
- the price may have been illegible and keyed in sightly wrong at BSA

**Comment by sebbacon** [comment]
Let me get this right: a pharmacy gets a prescription for Actavis; dispenses Morningside (and endorses with the brand and the price actually paid); and records an apparently random price, rather than the tariff price for Morningside (often quite a lot less than the that price?)

It is interesting that the Actavis one had all prescribing stopped when it stopped being available, and then went up again a year ago:

![image](https://user-images.githubusercontent.com/211271/61374122-7817df00-a893-11e9-9c84-5164e4de1a7c.png)

**Comment by sebbacon** [comment]
Regardless of what is getting dispensed, and how it's being priced, this looks like another SystmOne bug!


![image](https://user-images.githubusercontent.com/211271/61375195-2cb30000-a896-11e9-8178-55d9c9e99bed.png)

[notebook here](https://gist.github.com/sebbacon/317938750ea79e6291ae2cac51a0d31b)

**Comment by sebbacon** [comment]
Regarding Metabet, it's also interesting to note that the packaging for Sukkarto (the cheapest presentation) is identical to the Morningside Generic

![image](https://user-images.githubusercontent.com/211271/64000379-86e1ea80-cafd-11e9-93cf-fe1e32231b0c.png)


https://twitter.com/blmerriman/status/1167180801202642960

**Comment by sebbacon** [comment]
On this, SQL to find all VMPs with an AMP from more than one supplier:

```sql
SELECT
  descr,
  dmd2_amp.vpid,
  bnf_code
FROM
  dmd2_amp
INNER JOIN (
  SELECT
    vpid,
    suppcd,
    COUNT(*) AS num
  FROM
    dmd2_amp
  WHERE
    flavourcd IS NULL
    AND vpid != 7525511000001105
    AND bnf_code LIKE '0%'
    AND bnf_code NOT LIKE '09%'AND nm NOT LIKE '%caplets%'
    AND avail_restrictcd = 1
  GROUP BY
    vpid,
    suppcd
  HAVING
    COUNT(*) > 1) dupes
ON
  dupes.vpid = dmd2_amp.vpid
  AND dupes.suppcd = dmd2_amp.suppcd
ORDER BY
  dmd2_amp.suppcd,
  dmd2_amp.vpid,
  bnf_code;
```

Output [here](https://gist.github.com/dc3f762304a89b46091efb377fd40415)
