### ISSUE TITLE
403 error making requests from pandas

### ISSUE THREAD

**Issue by psychemedia** [ebmdatalab/openprescribing#187]
I'm getting a 403 error when trying to make an API request from python/pandas:

```
import pandas as pd

def op_spending_by_practice(ccg, bnfcode):
    url='https://openprescribing.net/api/1.0/spending_by_practice/?code={bnfcode}&org={ccg}&format=csv'.format(ccg=ccg,bnfcode=bnfcode)
    df =pd.read_csv(url)
    df['bnf']=bnfcode
    return df

op_spending_by_practice('10L', '0601')
```

The following workaround works:

```
import requests
from StringIO import StringIO

def proxy(url):
    return StringIO(requests.get(url).content)

...
df =pd.read_csv(proxy(url), parse_dates=['date'])
...
```

I'm not sure what User-Agent pandas is using, but it seems your API doesn't like it...

**Comment by evansd** [comment]
It turns out this was Cloudflare blocking all requests where the user agent contains `Python-urllib`.

We've disabled this behaviour by disabling the "Browser Integrity Check" option on the firewall settings page:
https://dash.cloudflare.com/29eda675cdba63fecfdeb3947b930874/openprescribing.net/firewall/settings

**Comment by psychemedia** [comment]
Ah... that's interesting... that could maybe help me with some of my other scrapers...
