### ISSUE TITLE
PPU: how to update equivalent formulations and other custom groups

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#1893]
When we implemented PPU, we included a number of formulation swaps that were clinically checked in order to ensure that they were appropriate.

It has been flagged that one potential saving (Tiotropium) is not currently showing on the PPU page, as technically the two inhalers have different BNF generic codes, due to one being 18mcg/dose and the other being 13mcg/dose - however both inhaler have the same delivered dose of 10cmg and can therefore be considered equivalent.

We need to check whether the identified google sheet  is the corect one, as @inglesp stated:
>>>PPU formulation swaps: is it possible there’s another spreadsheet that we’ve used, or that swaps have been added manually?  I’ve tried importing https://docs.google.com/spreadsheets/d/1SvMGCKrmqsNkZYuGW18Sf0wTluXyV4bhyZQaVLcO41c/edit#gid=1784930737 locally, and that creates 355 mappings, but there are 481 mappings in production, and those will all get deleted if I import that spreadsheet into production

**Comment by inglesp** [comment]
When I looked at this a couple of weeks ago, I said that importing the spreadsheet locally "creates 355 mappings, but there are 481 mappings in production".  This is because the command that imports the spreadsheet also creates a bunch of special case mappings, which didn't happen locally because I didn't have any presentation objects in my local database.  Discounting those special cases, there are 354 mappings in production.

The one mapping that's not in production is between `0301020Q0AAADAD` (Tiotropium_Pdr For Inh Cap 18mcg + Dev) and `0301020Q0AAABAB` (Tiotropium_Pdr For Inh Cap 18mcg), which are in the last two rows of the "Data from pivot table" tab in [this Sheet](https://docs.google.com/spreadsheets/d/1SvMGCKrmqsNkZYuGW18Sf0wTluXyV4bhyZQaVLcO41c/edit#gid=1784930737).

Data from that tab is already used in PPU calculations, as it is imported directly by the `import_ppu` command.  However, the code that drives the bubble charts uses data in the `GenericCodeMapping` table, and this has not been updated with the Tiotropium_Pdr mapping.  I could do this now, and, if we do this often, could add a Slack command to pull in new additions to that tab.

**Comment by inglesp** [comment]
> I could do this now

I've done this.
