### ISSUE TITLE
Opioids measure not showing correct presentations

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#1960]
I'm not sure if this is related to #1794 but the list of presentations on https://openprescribing.net/measure/opioidome/ is incomplete - it only includes _generic_ preparations, not branded.

This may be due to the way that the ome table is structured, as only generic presentations are listed.

**Comment by inglesp** [comment]
By "the list of presentations", do you mean the things in the table under "Presentations contributing to variation" at eg https://openprescribing.net/measure/opioidome/ccg/03T/?

**Comment by richiecroker** [comment]
I do

**Comment by inglesp** [comment]
It's not only the list of presentations contributing to variation that is incomplete, the measure calculation itself is going to be incorrect, as that uses the same list of presentations.

---

The presentations contributing to variation are those matching this query:

```
SELECT DISTINCT presentation, presentation_code
FROM hscic.bnf
JOIN ebmdatalab.richard.opioid_measure
ON CONCAT(
  SUBSTR(bnf.presentation_code,0,9),
  'AA',
   SUBSTR(bnf.presentation_code,-2,2)
) = CONCAT(
  SUBSTR(opioid_measure.bnf_code,0,11),
  SUBSTR(opioid_measure.bnf_code,-2,2)
)
```

This is the `numerator_bnf_codes_query` attribute of the `opioidome` measure, and is derived from the query that backs the [`opioid_total_ome`](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_sql/opioid_total_ome.sql) view.

When the measure was created, the `JOIN` condition was slightly different, but equivalent.  With new formatting:

```
ON CONCAT(
  SUBSTR(bnf.presentation_code,0,9),
  'AA%',
   SUBSTR(bnf.presentation_code,-2,2)
) = CONCAT(
  SUBSTR(opioid_measure.bnf_code,0,11),
  '%',
  SUBSTR(opioid_measure.bnf_code,-2,2)
)
```

In 1084c034, I reformatted the query, and also removed the `%`s, since outside of a `LIKE` clause, `%` doesn't mean wildcard.  (I should have smelled a rat here, sorry.)

@richiecroker Could you describe exactly how the measures in the numerator relate to those listed in the `richard.opioid_measure` table?  Some examples might be helpful here.  We can then work out what the correct query would be.

**Comment by richiecroker** [comment]
If you run the first query in BQ @inglesp it picks up brand as well as generic.

**Comment by richiecroker** [comment]
and the other two opioids measures seem to work correctly.

**Comment by inglesp** [comment]
> If you run the first query in BQ @inglesp it picks up brand as well as generic.

Oh, right.  So it does.  I'd only looked at the first ten or so, which are all generic, and then got distracted by the `%` thing.

**Comment by inglesp** [comment]
The fix is nice and easy.

The first query above is not quite the `numerator_bnf_codes_query` for this measure... but it should be.

It's currently selecting the distinct BNF codes from the `opioid_measure` view, when actually it should be selecting the distinct BNF codes from the `bnf` table that match the codes in the view.

Well spotted @richiecroker!

**Comment by inglesp** [comment]
I was also wrong about "the measure calculation itself is going to be incorrect", which is good.
