### ISSUE TITLE
Include closed practices in our measures, to be consistent in code

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#197]
There are > 400 practices which are marked "D" in `epraccur`, which means "Dormant".

It looks like these practices are no longer prescribing - see [this data](https://gist.github.com/sebbacon/f0edaf8506cee8c5fa83ae0cc1a70df1) showing all the dormant practices as of Feb 2016.  

They cover the full range of dates (i.e. there are practices that went dormant in 2010 right until 2016), and may of them were high-prescribing practices; the column `prescriptions_lost` estimates the number of prescriptions we would have expected them to make had they not stopped prescribing (2.4 million).

Sounds very much like we should be excluding these from our measures calculations (we currently only exclude "Closed" ones).  The challenge is that we are given dates for when a practice closed but not for when it went dormant, so we'd have to compute those.

**Comment by annapowellsmith** [comment]
What does the `total_items` field in that table mean? Is it the total prescriptions between August 2010 and the date they went dormant?

**Comment by sebbacon** [comment]
Yes.

**Comment by annapowellsmith** [comment]
Just re-scanned the measure calculation code, and [in fact we should exclude from percentile calculations any practice with a `calc_value` of null](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_measures.py#L365-L367). This means that in practice closed and dormant practices will be excluded from percentile calculations anyway, if they're not doing any prescribing. 

So basically, I don't think either including or excluding these types of practices is likely to make a significant difference to the calculated values. 

It would be better to include/exclude closed and dormant practice types consistently, but I think the easiest solution might be [to not exclude closed practices from the initial practice group](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_measures.py#L177-L181), then at least we're being consistent, though this would only really be for our internal understanding!

I think the advantage of explicitly excluding closed practices is that you don't get odd prescribing lag in the months after they've closed / become dormant, with just a few prescriptions trickling through and giving strange `calc_value` results due to low numbers, but I think the numbers are unlikely to be large enough for it to be worth spending time investigating dormant practices. 

(Aside: I do think we should continue to exclude non-standard practices explicitly from percentile calculations, because unlike closed/dormant practices they will have some prescribing, and prescribe items in low numbers and odd proportions.)

**Comment by sebbacon** [comment]
Actually, isn't it the [global centiles](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/import_measures.py#L402) that matter for cost-saving calculations (rather than the percentile rank you linked to)? Although not explicit in the code, it does seem that the pandas quantiles function ignores nulls in any case, so the outcome is the same.

:+1: to not exclude closed practices for consistency.

**Comment by annapowellsmith** [comment]
Now I feel sad that I used `df.quantile` rather than the already-calculated rank values to calculate global percentiles. Seems silly to do it twice. Oh well, I guess as long as it's tested and working it doesn't matter (and I've just checked and there is a null value in the test data, so it should be tested). 

Please go ahead and re-include closed practices if you wish - probably best to do this as a single PR, rather than bundling it in with everything else.

**Comment by sebbacon** [comment]
Wrapped up into #891
