### ISSUE TITLE
Add raw quantity data into our import 

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#1994]
The prescribing data contains raw quantity that is on the prescription. Currently we don't import this to the site as we aggregate Qty x Item. We do have a single month in BigQuery as a temporary table.

We agree that we will add raw quantity to the import so we can build new measures e.g. [dosette boxes](https://github.com/ebmdatalab/prescribing-queries/blob/master/Query%20Notebooks/Aspirin.sevendayrx/7%20Day%20Aspirin.ipynb) and also have in BigQuery  to facilitate analysis for blogs/papers.

**Comment by sebbacon** [comment]
I believe the right thing to do here is drop creating the view on the CSV which is the current month only, and create a new view which is all CSVs ever.  Which I *think* is possible with a wildcard.

**Comment by evansd** [comment]
I can't seem to get this to work.

I can create a new "external" table backed by CSV in Google Cloud Storage with the following schema:
```
[
  {"name": "Regional_Office_Name", "type": "STRING"},
  {"name": "Regional_Office_Code", "type": "STRING"},
  {"name": "Area_Team_Name", "type": "STRING"},
  {"name": "Area_Team_Code", "type": "STRING"},
  {"name": "PCO_Name", "type": "STRING"},
  {"name": "PCO_Code", "type": "STRING"},
  {"name": "Practice_Name", "type": "STRING"},
  {"name": "Practice_Code", "type": "STRING"},
  {"name": "BNF_Code", "type": "STRING"},
  {"name": "BNF_Description", "type": "STRING"},
  {"name": "Items", "type": "INTEGER"},
  {"name": "Quantity", "type": "INTEGER"},
  {"name": "ADQ_Usage", "type": "FLOAT"},
  {"name": "NIC", "type": "FLOAT"},
  {"name": "Actual_Cost", "type": "FLOAT"}
]
```
I enable Advanced Options and tick all the various "be lax about errors" boxes, plus tell it to ignore 1 header row.

The following GCS URL seems to work OK:
`ebmdatalab/hscic/prescribing/2017_0*/*Detailed_Prescribing_Information.csv`

But the more expansive URL doesn't work:
`ebmdatalab/hscic/prescribing/20*_*/*Detailed_Prescribing_Information.csv`

When I say "doesn't work" I mean that any attempt to query it returns `This query returned no results.` with absolutely no additional debugging information that I can find.

On further investigation I have discovered that I can trigger the problem with:
`ebmdatalab/hscic/prescribing/2017_1*/*Detailed_Prescribing_Information.csv`

So presumably it is something in one of `2017_10` `2017_11` or `2017_12` which is causing the problem. But the files are all over 3GB and I don't have time to download them all and figure out what the problem is.

**Comment by sebbacon** [comment]
Perhaps rename the `2017_` ones that don't work, and just provide the data starting in Jan 2018?

**Comment by evansd** [comment]
Not that simple, sadly. The following all work:
```
ebmdatalab/hscic/prescribing/2017_0*/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2017_10/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2017_11/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2017_12/*Detailed_Prescribing_Information.csv
```

But these don't work:
```
ebmdatalab/hscic/prescribing/2017_*/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2017_1*/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2017_1[0-9]/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2018_*/*Detailed_Prescribing_Information.csv
ebmdatalab/hscic/prescribing/2018_0?/*Detailed_Prescribing_Information.csv
```

The complete absence of any meaningful error message (in fact, the query doesn't actually error, it just returns zero results) combined with the fact that creating each table is a laborious pointy-clicky-copy-pasty affair in the web console makes it especially difficult to work out what's happening.

**Comment by evansd** [comment]
Finally got this working!

@brianmackenna There is now a table in BigQuery called `raw_prescribing` which contains quantity-level prescribing data as far back as we have it. Note that this doesn't have any of our BNF code normalisation applied to it, so we may want to create a view on this similar to the `normalised_prescribing_standard` view.

For future reference, the issue turned out to be something in the way wildcard GCS paths were being interpreted. Still not quite sure what was going wrong (due to complete lack of meaningful error messages) but in the end this path worked:
```
ebmdatalab/hscic/prescribing/20*Detailed_Prescribing_Information.csv
```

**Comment by evansd** [comment]
@brianmackenna There's now a `raw_prescribing_normalised` view in BigQuery. This contains the same fields as `normalised_prescribing_standard` except that instead of `quantity` it has `quantity_per_item` and `total_quantity`, which are hopefully self-explanatory.

The normalisation here means that we account for any BNF code changes and changes to CCG, PCN membership etc.

<details><summary>SQL for view</summary>

```sql
SELECT
  ccgs.regional_team_id AS regional_team,
  ccgs.stp_id AS stp,
  practices.ccg_id AS pct,
  practices.pcn_id AS pcn,
  raw_prescribing.Practice_Code AS practice,
  COALESCE(bnf_map.current_bnf_code, raw_prescribing.BNF_Code)
    AS bnf_code,
  raw_prescribing.BNF_Description AS bnf_name,
  raw_prescribing.Items AS items,
  raw_prescribing.NIC AS net_cost,
  raw_prescribing.Actual_Cost AS actual_cost,
  raw_prescribing.Quantity AS quantity_per_item,
  raw_prescribing.Quantity * raw_prescribing.Items AS total_quantity,
  PARSE_DATE("%F", REGEXP_REPLACE(raw_prescribing._FILE_NAME, "^.+/(20\\d\\d)_(\\d\\d)/[^/]+$", "\\1-\\2-01")) AS month
FROM
  ebmdatalab.hscic.raw_prescribing AS raw_prescribing
LEFT JOIN
  ebmdatalab.hscic.bnf_map AS bnf_map
ON
  bnf_map.former_bnf_code = raw_prescribing.BNF_Code
INNER JOIN
  ebmdatalab.hscic.practices  AS practices
ON practices.code = raw_prescribing.Practice_Code
INNER JOIN
  ebmdatalab.hscic.ccgs AS ccgs
ON practices.ccg_id = ccgs.code
```
</details>
