### ISSUE TITLE
dmd+d browser: supplier search

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2010]
I am trying to display all products from a supplier (in this case wockhardt). When I do the [search](https://openprescribing.net/dmd/advanced-search/amp/?search=%5B%22supp%22%2C%22equal%22%2C9301611000001104%5D) it returns zero products and the search criteria changes to "nothing" 

Colleagues at the BSA tell me this particular search is commonly requested by suppliers so they can identify all they AMPPs in the dm+d.

**Comment by inglesp** [comment]
I laughed out loud when I worked out what the problem was.

The supplier "Wockhardt UK Ltd" had ID 9301611000001105, but when you submit a search for it, the query `["supp","equal",9301611000001104]` is sent to the server.  This explains why no results are found, and why the dropdown text changes to "Nothing" (because there is no supplier with that ID).

This happens because deep inside the library we use to build the search interface, there is a call to `parseInt()` on the value of any search parameter that's an integer, and...

```
>> parseInt(9301611000001105)
=> 9301611000001104
```

The fix is to pretend that the options are not integers, and then everything works as it should.
