### ISSUE TITLE
Text changes on home page and analyse page

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#211]
Can you add a link to the how to use the analyse search somewhere on the analyse page? (https://openprescribing.net/docs/analyse/)

**Comment by annapowellsmith** [comment]
Hey @lmfrench, please could you make this two separate tickets? Sorry, we are EXTREMELY STRICT about keeping tickets about single issues. It's a programmer thing :)

**Comment by annapowellsmith** [comment]
Some further requests from Ben, so the final list of tasks is this:

1. Add a link to "how to use the analyse search" somewhere on the analyse page: (https://openprescribing.net/docs/analyse/)
2. Add the following to the home page: "Use our data: Got a tricky query for the data? We can provide custom extracts, we know the data well, and we’re keen to collaborate with academics and clinicians. Get in touch to find out more." and "How to cite: If you use our data or graphs, please cite as 'OpenPrescribing.net 2016, Anna Powell-Smith and Ben Goldacre', so that others can find us and use our tools."
