### ISSUE TITLE
Come up with decent "change-over-time" measure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#217]
We've said one of the things we'll draw attention to in the monthly emails is where a CCG (or practice) has changed rapidly over time in comparison with their peers.

I've tried implementing this as a line of best fit (least squares) over the last N datapoints. 

[Here is a CSV of CCGs ordered by gradient](https://gist.github.com/sebbacon/1d4c3f360fbaecf13ffe5076395bc450) over the last 6 months.

It includes URLs so you can eyeball the charts in question.

The suggestion is to only highlight ones where the gradient is `> 20` or `< -20` (i.e. the top and bottom few in that CSV).

However, eyeballing the graphs, it feels to me like a 6 month period is not sufficient to pick out trends.

Thoughts?

Connected to #151

**Comment by annapowellsmith** [comment]
Great to see this. 

Agree that it doesn't feel right! How does it change if you try a 12-month or 18-month period?

**Comment by Bengoldacre** [comment]
It won't be perfect, and we'll need to iterate. Many of the graphs I looked at here seemed like they were picking up something useful, but I didn't look at comparators where the same coefficient was lower for the same measure. The issue here is the sensitivity, specificity, and positive predictive value of the screening test we use for "movement", but compared against the gold standard of whether a human eye agrees there's something worth noticing, so it's always going to be imperfect. Anyway, I've done an email to Raf and Richard the stats folk to see if there's someone specific they can give us to help think through this. I slightly wonder if a simple "decile over past 3 months" vs "decile of preceeding 3 months" (or 6, etc) is easier, more transparent, and equally effective.

**Comment by annapowellsmith** [comment]
Yes, I agree with Ben that windowing might work better. 

If it's not incredibly time-consuming, could we look at:

- Line of best fit over preceding 12 months
- % change between the mean decile over past 6 months vs. the mean decile over the 6 months before that

**Comment by sebbacon** [comment]
So the two methods we're trying, both of which  equates to a measure of percentile drop/gain, are:

1. Gradient of lines of best fit of percentiles over `X` months
2. Difference between the means of the percentiles during the first `X/2` months and the second `X/2` months 

I've written code to help us compare them both using periods of 6 and 12 for `X` and pushed as web pages so we can link to specific examples (using the `[link]` link). 

Graphs link through to the CCG page on the live site.

Note the sort buttons at the top; click twice to reverse sort order (by default it's unsorted). The "residuals" sort option is there to help think about if residuals on the line of best fit is a good way of filtering out false positives, and only applies to method 1.

* [Method 1, 6 month window](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-6-month-method-1.csv.html)
* [Method 1, 12 month window](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-12-month-method-1.csv.html)
* [Method 2, 6 month window](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-6-month-method-2.csv.html)
* [Method 2, 12 month window](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-12-month-method-2.csv.html)

## Observations
* Approach 1 definitely feels more useful over a 12 month period than a 6 month period
* I'd say jettisoning fits with residuals of over 2000 in approach 1 with 12 months would definitely prune out some false positives in Approach 1
* Using Approach 2 results in far fewer possibly-interesting-changes (7 over 6 months, 12 over 12 months; compared with 129 over 6 months and 124 over 12 months for approach 1) -- is this fewer false positives, or fewer true positives?
  * For example, from eyeballing, you'd expect [this measure](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-12-month-method-1.csv.html#data-12-month-method-1_05Q_ktt8_antidepressant_first_choice) (picked up by Approach 1) to appear in Approach 2 data, but it doesn't.  If we look at the last 12 percentiles, they're `[85, 82, 82, 77, 72, 68, 73, 64, 64, 65, 61, 62]`, with the mean of the first 6 being 78 and the last six being 65 -- a change of 13. However, if you compute the least squares, you get a drop from 84 to 59 (over our threshold of 20) with a residual of 69. Which approach is more "right" with respect to that data?
* The human eye might sometimes disagree with the change when perhaps it should -- particularly where the deciles are quite close together, *and* have a lot of co-variance. For example, [this](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-6-month-method-1.csv.html#data-6-month-method-1_04Q_ktt9_antibiotics) shows a very good fit and a 26 centile drop, but it's not at all evident in the chart. Do people think that one *does* look like an interesting drop, or not (because the centiles are so close anyway)?
* It may be an advantage of method 1 that it gives us a measure of residuals, because that could lead us to reject some things that are probablyl too noisy to care about, but still happen to have large differences between their two means. Comparing the same output for a single measure between the two methods helps verify this, e.g. [method 1](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-12-month-method-1.csv.html#data-12-month-method-1_10T_ktt10_uti_antibiotics), [method 2](https://bl.ocks.org/sebbacon/raw/9d6b810c0fd3d5f87809f0b2bc6f03a7/data-12-month-method-2.csv.html#data-12-month-method-2_10T_ktt10_uti_antibiotics)

It would be useful if others could spend a while looking at some of these measures that have been found, and try to pick out possible false positives).

**Comment by annapowellsmith** [comment]
This is excellent, great work 😄 

> I'd say jettisoning fits with residuals of over 2000 in approach 1 with 12 months would definitely prune out some false positives in Approach 1

I agree. Could even be more conservative and throw away everything >1200 or so. 

> Using Approach 2 results in far fewer possibly-interesting-changes (7 over 6 months, 12 over 12 months; compared with 129 over 6 months and 124 over 12 months for approach 1) -- is this fewer false positives, or fewer true positives?

I agree that Approach 2 does feel like it's losing some potentially valid changes (which makes sense). What happens if we use Approach 1 and throw away everything with an absolute change of <20, and residuals >1200?

> The human eye might sometimes disagree with the change when perhaps it should -- particularly where the deciles are quite close together, and have a lot of co-variance. For example, this shows a very good fit and a 26 centile drop, but it's not at all evident in the chart. Do people think that one does look like an interesting drop, or not (because the centiles are so close anyway)?

I think that's because those deciles are just too close together, and that's due to the infuriating bug in Highcharts where it insists on setting the x-axis min to 0 for that particular chart. It's the Highcharts display bug that is the issue. 

> It may be an advantage of method 1 that it gives us a measure of residuals, because that could lead us to reject some things that are probablyl too noisy to care about, but still happen to have large differences between their two means. Comparing the same output for a single measure between the two methods helps verify this, e.g. method 1, method 2

Yes, this is definitely an advantage. 

I would like to see what happens if you use Approach 1 over *both* 6 months and 12 months, and throw away everything with an absolute change of <20, and residuals >1200 (randomly picked numbers). 

Also, it would be very useful to be able to fiddle with both absolute change, and residuals, simultaneously in the front-end, if you have the energy to engineer that!

**Comment by sebbacon** [comment]
Thanks for the feedback.

> I would like to see what happens if you use Approach 1 over *both* 6 months and 12 months

I don't understand how this is different to what I've already done. Can you expand? 

>  and throw away everything with an absolute change of <20, and residuals >1200 (randomly picked numbers).

We're already throwing away < 20, so if you order by residual you can get an idea of what this would look like.

**Comment by annapowellsmith** [comment]
> I don't understand how this is different to what I've already done. Can you expand?

Sorry - I mean combine the two.

> We're already throwing away < 20, so if you order by residual you can get an idea of what this would look like.

I can see some with change of ±17 and ±18? But point taken, maybe those are fine. Anyway I think we can definitely throw away higher residuals - it would be good to do that and then eyeball the results.

**Comment by sarahlstevens** [comment]
I like the gradient approach with removal of cases with high residuals (probably because it's similar in approach to some other formal stats methods). I wonder how the above would be affected if you were to shorten the second time window? e.g. gradient based on 12 months vs. gradient based on 3 months. If the aim is to be able to flag changes quickly, then a 12 month time window might be too long?

Another approach to try to account for the noisy measures in one go would be to look at the mean **absolute** change from one month to the next over 12 months compared to the mean absolute change of the following few months. Noisy cases will have a larger mean absolute change from month to month, so a much larger degree of change will be needed to flag these as interesting. May through up some false positives if data becomes less/ more noisy over time, but from the plots I've seen that's not common.

**Comment by sebbacon** [comment]
Update: the [current implementation](https://github.com/ebmdatalab/openprescribing/blob/28290f2151519d173747f41c7eabe0b81240ada9/openprescribing/frontend/views/bookmark_utils.py#L184-L205) uses a line of best fit over a 9-month period, throwing away measures where the residuals are at least 1200.

**Comment by alexwalkercebm** [comment]
I think I’ve worked out an alternative mechanism to detect changes. I was reading about statistical process control methods and came across CUSUM (explained okay on Wikipedia https://en.wikipedia.org/wiki/CUSUM), which involves calculating the cumulative degree of deviation from a reference value (for us the percentile that a practice/CCG starts in). It’s not a ‘significance test’ method, but there are some possible advantages over the previous method:

--It’s independent of the length of time that the change takes place over. It should be equally good at detecting small changes over a long period of time as it is at detecting large changes over a short period. Whether this is an advantage or not depends on what sort of changes we’re looking for.
--It takes into account the number of prescriptions for the drug and CCG/practice in question, so it may help to some extent with big variations due to small numbers, though could do with assistance thinking this through. Extremely small numbers might still be problematic?
--It’s potentially more sensitive to changes, but this can be tweaked. It might be better/worse at detecting interesting changes, or might just detect different ones.

## Example
I think I've managed to fit this method with our needs. The example is in terms of ratios of drug use (e.g. Cerazette vs. Desogestrel), but it’s actually simpler for other things, like absolute drug use/costs. I’ve used CCG here, but could substitute practice:

1.	Determine what percentile a specific CCG is in at month 0 (e.g. 75th)
2.	Calculate the _expected_ number of prescriptions for Cerazette for the specified CCG, within the percentile determined above, for month 1 onwards.
a.	CCG denominator * 75th percentile numerator / 75th percentile denominator
b.	This expected value will change month by month in accordance with changes within that (75th) percentile
3.	Calculate the excess prescriptions within each CCG, for month 1 onwards
a.	Observed number of Cerazette prescriptions - expected
b.	This can be +ve or -ve
4.	The ‘S’ value is then the calculated for each month consecutively: 
a.	S0=0
b.	Sn=max(0, Sn-1+excess Cerazette prescriptions) –to determine if an increase has occurred
c.	Sn=min(0, Sn-1+excess Cerazette prescriptions) –to determine if a decrease has occurred
5.	The critical value is the threshold of S at which a change is determined to have taken place
a.	I think if we determine the threshold value based on average number of Cerazette prescriptions for that CCG/practice (e.g. X * the average) then it should give reasonably consistent threshold levels and results across different drugs and CCGs/practices. X can be tweaked to determine the sensitivity/specificity of the alert.
b.	Could also use average over the previous few months to respond to big changes over time
6.	Once an alert has been activated through S reaching the threshold, it is determined that a change has taken place, the value of S is reset to 0 and the determining of reference percentiles starts again.
a.	Alternatively, if we’re only interested in one alert per drug/CCG, then we could just stop once an alert has been triggered.

This just about works in my head, but any thoughts are welcome. Let me know if any/all of this doesn’t make sense. Both methods could be valid, but could try it and compare to the output from the current method?

**Comment by Bengoldacre** [comment]
interesting. not able to think this thru thoroughly before coffee but, after road-testing this, then to deliver a practically useful service we might find we want to consider different thresholds for small and large units ie CCGs and practices, to reflect trade-offs between signal and noise with different volumes of data and, by extension, different volumes of alerts. i.e. arguably people might tolerate a larger number of less predictive alerts in low data volume settings where they're not overwhelmed by alerts. mm.

**Comment by alexwalkercebm** [comment]
The example above does already adjust the threshold according to the volume of prescriptions, but yes the critical part that will take some iteration is deciding where the threshold should be and whether this should change for different situations. We could even have a sensitivity slider so that people can adjust according to their needs.

**Comment by Bengoldacre** [comment]
do u feel ready to instantiate this in code and roadtest it?

**Comment by Bengoldacre** [comment]
i'm pretty sure there's CUSUM in numpy for later, and i'd be amazed if someone hadn't made a library in Stata too.

**Comment by alexwalkercebm** [comment]
I could do it in Stata, so will have a go. Python would require substantial hand-holding (starting with from basically nothing). The actual maths required is pretty simple.

**Comment by sebbacon** [comment]
Not sure I can add much useful as I don't have a naturally statisticky brain and would have to think about it for an hour to get it properly.

Regarding python implementations, [this](https://github.com/bzimmer/changepoint) would appear to be one, though strictly speaking it is an implementation of [this](http://www.variation.com/cpa/tech/changepoint.html) which appears to include CUSUM as a subset of the algorithm plus bootstrapping to add a confidence level (is that of interest too?)

**Comment by sebbacon** [comment]
p.s. I won't really understand this (well enough to comment on it cogently, in any case) until I've spent an hour frowning at it.  So all I can say is, if you think it's promising, let's try it against some real data and see how it works....

**Comment by alexwalkercebm** [comment]
I'll have a crack in Stata. Hard to judge its merits without seeing outputs.

**Comment by alexwalkercebm** [comment]
@sebbacon I've done some reading and learning about python and am getting there with understanding it. I'm starting to have a go at converting my stata CUSUM implementation into python. (The implementation you posted above needs some adapting as it uses a fixed reference value, but we need a dynamic one.)

However, as I'm still learning and there seem to be various ways of handling data within python and also with SQL, I was wondering if you could advise about the best way to get the initial data managed. The data I need initially for a given measure are:

1. An array with the numerator/denominator ratios (calc_value, as created by this SQL query: https://github.com/ebmdatalab/prescribing-queries/issues/25) for each practice, for each month. I don't need the numerators/denominators themselves anymore as I'm going to try a different variation of CUSUM. The query above spits out a single column of calc_values so it just needs dividing by practice/month
2. An array containing the percentile that each practice is in each month
3. An array containing average calc_value associated with each percentile, for each month

I guess some or all of this is calculated for the site anyway? If possible would be good to copy that rather than try to work it out using my limited python/SQL skills.

**Comment by sebbacon** [comment]
@alexwalkercebm we can talk about this tomorrow - but briefly - isn't all that data in the JSON available via the API? If so -- that's what I would use. Can show you how tomorrow.

**Comment by alexwalkercebm** [comment]
Thanks! Very probably, but some guidance would be very useful.

**Comment by alexwalkercebm** [comment]
I've now converted my stata code into python at this link:
https://gist.github.com/alexwalkercebm/7a917b4c456c718e89d8412b9ac61745#file-cusum-ipynb

Any suggestions welcome!

## Notes

- It's worth trying out for a variety of measures and CCGs/practices, it's fairly easy to change these
- It works for most cases pretty well, but there are a few exceptions that I've found so far, notably:
  - There are some occasions where it detects a very small change over a long period, and triggers an alert where the actual change is a couple of percentiles - could potentially just exclude these alerts.
  - If the data start out very noisy and then become less noisy, this sets the threshold extra high and this could potentially mask changes
- The code works for most practices, but throws up an error at the moment if the data are missing for the first month (or more)

**Comment by sebbacon** [comment]
[Here](https://github.com/ebmdatalab/CUSUM/blob/master/CUSUM-%20pandas.ipynb) is Alex's latest version, to be implemented.
