### ISSUE TITLE
Come up with a way of deciding if measures are significant

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#218]
When looking at data at a CCG level, there is usually enough data to make comparisons and inferences possible.

At a practice level, there are often much lower numbers -- for example, only three patients are prescribed desogesterol (the denominator), and all of these are Cerazette (the nominator), so the measure is consistently 100% (or 0% in months where there is no repeat prescription).

Here is a less extreme example from [this page](https://openprescribing.net/practice/E85058/), showing a measure that our current ([proof-of-concept](https://github.com/ebmdatalab/openprescribing/issues/217)) algorithm considers to be an example of a measure value increasing consistently over 6 months.

![image](https://cloud.githubusercontent.com/assets/211271/19441581/1091fb3a-947e-11e6-8249-f8ee95a2a309.png)

Measures where a value is frequently 100% or 0% are likely to show false positives, for example.

@Bengoldacre suggested using the standard error as a way of identifying such false positives, but it was a while ago and my notes don't make sense.

**Comment by annapowellsmith** [comment]
I think the algorithm was basically "if the standard error is outside the 10th and 90th percentiles, don't bother". But Ben can confirm the details.

**Comment by Bengoldacre** [comment]
This is a good one to involve Sarah Stevens on once she's signed up. 

Do you mean "when do we flag measure/practice pairs as "_caution, low numbers_"? If so then our candidate first answer to try here, via stats prof Richard Stevens, was "is the standard error bigger than the point estimate?" and then see if that meaningfully captures cases where low numbers make the data very hard to interpret.  

So, for n/N, if the point estimate is 0.28 and the SE is 0.3 then flag it as _"caution, low numbers"_. Equally where the point estimate is 0.72 the same applies.

However this falls down for situations where n/N = 0 or 1, where things will always get trickier. Let's see if Sarah has any suggestions?

**Comment by annapowellsmith** [comment]
@sebbacon if you need to get on with implementing this, for the moment you could just use: "if the numerator for this measure/organisation is <10 items (or equivalent quantity, for quantity-based measures) in 3 or more of the past 6 months, don't include this measure in this organisation's alerts or dashboard". 

I think that would be a perfectly OK start. It would be a good addition to the dashboards sooner rather than later, actually.

We should also think about metrics for whether an overall measure is actually sensible - e.g. as another sensible good-enough-for-now metric, if more than 50% of the organisations involved fail the above test, we may not want to use it. (This might disqualify quite a few of our current measures for GP practices.)

**Comment by sarahlstevens** [comment]
One option is to work with the logit transformation of the scores. For all values that are >0 and <100%, just use the logit transform: log(p/[1-p]) (0<p<1). For the values at the extremes use (0 and 1) use : log((p+[0.5/n])/(1-p+[0.5/n])) where n is the number of people on which you're evaluating. This translates the proportions to a linear "score" which can then be used in the usual way, with the SE approach Ben mentions above. See http://www.bmj.com/content/352/bmj.i1114.long for a longer explanation

**Comment by sarahlstevens** [comment]
This approach also has some nice properties in that a practice will have a larger score if it prescribes 100% branded drugs to 40 patients (e.g) vs a practice prescribing 100% to only 5 patients.

**Comment by sebbacon** [comment]
Thanks all.

[This spreadsheet](https://github.com/ebmdatalab/openprescribing/files/535862/cephalosporin.xlsx) contains the data for one month.  

The uncorrected (non-logit) scores are in column D and range from 0 to 1, with a median of 0.08. The standard error is 0.0005.

The logit-corrected scores are in column E and range from -9.6 to 9.6 with a median of -2.45. The standard error is 0.0101.

Using the approach Ben mentions, as I understand it, we would reject any rows where the value is less than 0.0005 or greater than 0.9995. You can see its effect in column G -- which in this case amounts only to those rows where the value is 0.

Using the logit-corrected scores, I'm less clear how I'm filtering. I took a stab at defining it as less than (`min_logit + logit_std_err`) or greater than (`max_logit - logit_std_err`) (see column F) but that seems unlikely to be correct given the tails of the value distribution are now approximately exponential.

I'm positive I've got the wrong end of the stick here. @sarahlstevens, could you take a look at my spreadsheet and put me right? Thanks!

**Comment by sebbacon** [comment]
@annapowellsmith, regarding the < 10 items in the numerator suggestion: I agree with your hypothesis, but it is complicated by the fact that the numerator is frequently `quantity`, is often (for example) 60 pills in one prescription event (`item`). You allude to this problem when you say we should use the "equivalent quantity, for quantity-based measures", but I'm not sure what this means, given pack sizes vary by brand, prescription, etc. I *think* we'd only ever want to look at item counts for this to work? If so, we'd want to add `SUM(items)` across the board to measure values.

**Comment by annapowellsmith** [comment]
I think you can just ask Richard what a sensible quantity would be in each case to indicate with reasonable certainty that it's more than a few prescriptions. If it's not possible because the measure is looking at different medications then yeah, look at items. But I'd hope that any quantity-based measure would already have considered this possibility, and only be used in situations where quantities can be compared consistently.

**Comment by sarahlstevens** [comment]
Ok, so I've given this a bit more thought and my approach isn't going to work sensibly for flagging individual practices. Richard's suggestion is great for continuous measures but falls down for proportions close to 0.5/ because even if a 50% proportion is only based on two items, the SE will always be less than 0.5. One suggestion is to calculate the number of items required to being able to say we are confident in a proportion from a practice to within (say) +/- 5%, but this will again be an issue with proportions <5% or >95%. Instead we can determine how many items are needed to be confident to within +/- 0.1p. So for a 50% proportion, we want to be confident within +/- 5%, but for a 20% proportion we want to be confident to within +/- 2%. We can debate whether we use 0.1p or something larger. This will mean however that extreme proportions will need a larger number of items for practices not to be flagged. With this approach we would need to have the number of items exceeding (1.96^2*(1-p))/(0.1^2*p) for 0<p<0.5 (and then (1.96^2*p)/(0.1^2*(1-p)) for 0.5<p<1) where the 0.1 can be changed depending on how strict you want to be. At the extremes we could treat 0 and 0.01 and 1 as 99.99 for example. Or if you want to the number to be the same across the practices, I would suggest working out the number for 50% (once a desired level of precision has been agreed) and applying it uniformly.

**Comment by sebbacon** [comment]
Thanks @sarahlstevens - I'm on leave most of next week so will come back to you on this at the start of Nov.

**Comment by annapowellsmith** [comment]
Oops I just noticed I said "numerator" in my suggestion above - it should have been denominator! Doh.

**Comment by HelenCEBM** [comment]
Closing as we have implemented this with the CUSUM alerts
