### ISSUE TITLE
Data for 2014 in normalised_prescribing is double what expected

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#2648]
Having run some searches in `prescribing_normalised` yesterday, all 2014 data seems to be double what expected.  Looking at number of rows, this also seems to be the case.  Has the 2014 data been duplicated?

![image](https://user-images.githubusercontent.com/18683239/82431821-131ab000-9a87-11ea-8d46-c89862f16056.png)

**Comment by inglesp** [comment]
Well spotted.  This is because we were originally promised republished data going back to 2015, but we were actually given data going back to 2014.  The data in the view comes from taking the pre-ODD data from the original prescribing table (but only for months when we don't have post-ODD data) and the post-ODD data from the new prescribing table.

PR incoming.

**Comment by inglesp** [comment]
PS it's great to have you back @richiecroker!

**Comment by inglesp** [comment]
Should be fixed.

PS @richiecroker for issues like this where a query's returning something unexpected, it's helpful to include the SQL in the issue, so that we can verify that a fix has worked.

**Comment by richiecroker** [comment]
Thanks @inglesp - it's nice to be back (however part time it is!)
For info, this was the SQL I used:
```
select month, count(*) as count_rows
from hscic.normalised_prescribing
group by month
order by month
```
