### ISSUE TITLE
Start analysis of search behaviour

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#273]
I've made a start at documenting the data we capture in a new github Wiki, [here](https://github.com/ebmdatalab/openprescribing/wiki/analytics).

Per the "Exporting raw data" section there, it is not possible to download more than 5000 rows of data without paying Google for a *360 Analytics* account. By good fortune we have had fewer than 5000.

The data we're interested in analysing is concatenated together in "query string" format (joined with `&` and `=`). I could write some simple python code to change that so it's in separate columns, when we need this.

@Bengoldacre what did you want to happen as the next step(s) here?

**Comment by lmfrench** [comment]
I can have a go at writing some code to separate it into columns ((has been a long time since I coded anything other than SQL - I've used perl rather than python but would be nice to see if I can still remember how to code!)

**Comment by Bengoldacre** [comment]
great thanks. can we pls grab and parse into a two way table where for every analyse view we have a column for all variables, i.e. org,  orgIds, numIds, denom, denomIds. We need to think about how to split out for analyses. Ultimately we'll want to do things like:

1. most common chapters, paras, sub pars, chemicals in numerator
2. most common chapters, paras, sub pars, chemicals in denominator
3. what proportion use population denoms instead of drugs
4. most common org IDs
5. distribution of frequency of org IDs

To account for appearance of multiple chemicals / ch's etc in a single numerator and denom for some searches we should prob do (for simplicity) most common chapters, paras, sub pars, chemicals to _appear_ in numerator. i.e. appear at all even in combination with others.

**Comment by sebbacon** [comment]
OK, over to you @lmfrench. I'm afraid you'll have to download the raw data in batches on 5000 -- I think that means 10 batches so not to onerous.

If it's loads more I could write a script to do it but that would prob take 2 or 3 hours, so best to try the manual approach first.

Note you can also add in some other analytics dimensions into the data. One thing I've played with for example is applying a "NHS" segment so we can compare the two (albeit we don't actually know what "NHS" means yet -- presumably from inside N3 but we never got to the bottom of that)

**Comment by Bengoldacre** [comment]
ah that's great, but can we link "NHS" to each analyse page view? i thought slicing and dicing like that was verboten in google analytics..

**Comment by sebbacon** [comment]
Yes because it's not personally identifying.  Other things we can add are things like if it's a referral or from organic search, geographic region, etc etc.
