### ISSUE TITLE
Migrate to using Github Actions

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#2781]
Move OpenPrescribing CI from Travis to Github Actions

I quite like [this](https://github.com/opensafely/opencodelists/blob/master/.github/workflows/main.yml) way of doing things but that also involves adding new tooling; let's start with reproducing exactly what we've got

**Comment by madwort** [comment]
Ok, I think https://github.com/ebmdatalab/openprescribing/pull/2783 now reproduces exactly what we've got in Travis. I've also fixed a few minor bugs/warnings in the tooling along the way. 

So what I think we're doing currently is something like:
* the github action creates docker container with their standard ubuntu image, which runs docker-compose, which creates a nested docker container consisting of the openprescribing image & a postgis image.

I think this takes slightly longer than necessary because docker-compose is going to need to download the openprescribing & postgis images from scratch from upstream for every run. 

Other options for implementing this that I think would speed this up:

1. cache the docker images across github action runs. Presumably it's possible with https://github.com/actions/cache , but maybe nobody's actually done it yet? https://github.community/t/github-action-docker-compose-cache/16887
2. have the github action create a docker container with the openprescribing image, with a service container, thus moving what is currently in docker-compose to be directly in the github action https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers - I /think/ this would allow github to cache the docker images & speed up CI runs, because the instance of docker that's downloading the images is github's, not ours.
3. deploy the app directly into the github action's standard ubuntu image - I think this is what https://github.com/opensafely/opencodelists/blob/master/.github/workflows/main.yml is doing - this would allow us to easily cache openprescribing's dependencies as opencodelists does

**Comment by madwort** [comment]
Another possible criteria - testing the codebase against multiple versions of python may be easier with (3)

**Comment by madwort** [comment]
related stretch goal, depending on what direction we take: [Any time you change the npm or pip dependencies, you should rebuild the docker image used by the tests to improve runtime performance of travis.](https://github.com/ebmdatalab/openprescribing#using-docker) - we can probably automate this with github actions?

**Comment by sebbacon** [comment]
I can't think why building the app directly wouldn't work but there are perhaps some benefits to being able to orchestrate everything with a `docker-compose up`... I'm sitting on the fence on that one.

Regarding the your most recent comment, we could simply build the docker image directly in the github actions; if we use https://github.com/whoan/docker-build-with-cache-action then the *layers* will be cached giving us performance *and* up-to-date goodness?  We could piggy-back off the same logic by having an almost-empty dockerfile for postgres? Not sure if that's a clever idea or a "clever" idea.

**Comment by madwort** [comment]
Related: [slack notifications](https://github.com/ebmdatalab/openprescribing/pull/2799)

**Comment by madwort** [comment]
I think this is done
