### ISSUE TITLE
Semaglutide injection measure definition including tablets

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/openprescribing#2939]
@andrewbarron85 has drawn my attention to the fact that the [semaglutide measure](https://openprescribing.net/measure/semagglutidequantity/definition/) is now including tablets ([NLP STP example](https://openprescribing.net/measure/semagglutidequantity/stp/E54000028/))

A quick review looks like we did not foresee release of tablet preps when we wrote the measure. The very quick fix is to include `bnf name NOT LIKE tab`. Other fixes include using `dmd.formroute` or curation of bnf codes.

**Comment by brianmackenna** [comment]
We thought #2940  fixed this issue but tablets are still being reported on the [measure](https://openprescribing.net/measure/semagglutidequantity/national/england/#semagglutidequantity).

**Comment by inglesp** [comment]
You're missing a `\n` from [this line](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/measure_definitions/semagglutidequantity.json#L46).

Because it's missing, the [generated SQL](https://openprescribing.net/measure/semagglutidequantity/definition/) is:

```
SELECT
     CAST(month AS DATE) AS month,
     practice AS practice_id,
     SUM(total_quantity) AS numerator
 FROM hscic.raw_prescribing_normalised
 WHERE quantity_per_item>3 AND bnf_code LIKE '0601023AW%' --Semaglutide AND bnf_name  LIKE '%inj%'
 GROUP BY month, practice_id
```

and not:

```
SELECT
     CAST(month AS DATE) AS month,
     practice AS practice_id,
     SUM(total_quantity) AS numerator
 FROM hscic.raw_prescribing_normalised
 WHERE quantity_per_item>3 AND bnf_code LIKE '0601023AW%' --Semaglutide
       AND bnf_name  LIKE '%inj%'
 GROUP BY month, practice_id
```

That is, everything after the comment is erroneously included in the comment.

See [lpneedles.json](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/measure_definitions/lpneedles.json#L36) for where this is done correctly.

I'm going to check all other measures to see whether we hit this elsewhere.

If we get more funding, reworking measure definitions is top of my wishlist.

**Comment by richiecroker** [comment]
Thanks @inglesp: [hopefully fixed and PR created](https://github.com/ebmdatalab/openprescribing/pull/3066).

**Comment by inglesp** [comment]
This is the only measure affected.

```
# check_comments.py
import glob, json


for path in glob.glob("*.json"):
    with open(path) as f:
        measure_def = json.load(f)
    
    for key in "numerator_where", "denominator_where":
        if key in measure_def:
            for row in measure_def[key ][:-1]:
                if "--" in row and row[-1] != "\n":
                    print("-" * 80)
                    print(path)
                    print(row)
```

```
$ python check_comments.py 
--------------------------------------------------------------------------------
semagglutidequantity.json
bnf_code LIKE '0601023AW%' --Semaglutide
--------------------------------------------------------------------------------
semagglutidequantity.json
bnf_code LIKE '0601023AW%' --Semaglutide
```

**Comment by richiecroker** [comment]
this is now fixed.
