### ISSUE TITLE
Missing STP codes in new CCGs

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#3146]
We had an email from a user:

>Hi,
>
>If I look at London Commissioning region the data suggests £112,111 on 488 items. 
>If I try and drill down and look at all 5 London ICS, only 3 ICS&#39;s show up at 37k as total Am I doing something wrong? Or is there a problem?

It looks like the two London ICS/STPs which have no data are the two new organisations which formed in April 2021.

Looking more closely at BQ, it seems that none of new CCGs (with ANANA codes) have an STP attached:

![image](https://user-images.githubusercontent.com/18683239/124627070-251c0580-de77-11eb-9b40-0e54e26338c4.png)

**Comment by inglesp** [comment]
We haven't imported the latest STP mapping.

However:

```
(.venv38) hello@largeweb2:/webapps/openprescribing/openprescribing$ python manage.py import_stps --filename ~/openprescribing-data/data/stp_mapping/2021_04/stp-partners-master.xlsx 
__str__ returned non-string (type NoneType)
Traceback (most recent call last):
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/db/models/base.py", line 519, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type NoneType)
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/pipeline/management/commands/import_stps.py", line 44, in handle
    stp.code = stp_code
AttributeError: can't set attribute
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by evansd** [comment]
So it looks like we've created a field called `code` to store the ODS code in, but we're currently shadowing that with a property decorator which just returns the ONS code.
https://github.com/ebmdatalab/openprescribing/blob/1d869d431b7f070b0be2830b97458799e8146df1/openprescribing/frontend/models.py#L104-L125

I think this was done because we didn't have ODS codes for STPs when we first launched the feature.

The simplest way to move forward here is just to comment this line out:
https://github.com/ebmdatalab/openprescribing/blob/1d869d431b7f070b0be2830b97458799e8146df1/openprescribing/pipeline/management/commands/import_stps.py#L44

i..e. don't attempt to set the ODS code.

The right long term fix is to switch to using ODS codes as the primary key for this table (as the comment recommends) but that's more work than we can do right now.

**Comment by inglesp** [comment]
Thanks @evansd.  In the past I'm pretty sure we've commented out the `code` property on `STP`.

https://github.com/ebmdatalab/openprescribing/blob/1d869d431b7f070b0be2830b97458799e8146df1/openprescribing/frontend/models.py#L123-L125

I've just tried that, and it fails with:

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "frontend_stp_code_568ab922_uniq"
DETAIL:  Key (code)=(QHM) already exists.
```

This is because for several STPs, the ONS code has changed.

We're using the ONS code as the primary key (the ODS codes weren't published when we began this work), and we also have `unique=True` on the ODS code field.

There are foreign keys from `PCT` and `MeasureValue` to `STP`, so we'll have to update these FKs for the following:

ODS code | old ONS code | new ONS code
-- | -- | --
QHM|E54000049|E54000050
QNX|E54000033|E54000053
QOQ|E54000006|E54000051
QWO|E54000005|E54000054
QXU|E54000035|E54000052

**Comment by inglesp** [comment]
I've imported the STP mappings and have reimported the measures.  However, I didn't upload the STPs to BigQuery first, so importing the measures hasn't worked.

**Comment by inglesp** [comment]
I've uploaded the STPs to BQ and have rereimported the measures.  @richiecroker can you check the data on the site is as you'd expect please?

**Comment by richiecroker** [comment]
Sorry @inglesp didn't see your last comment.  Yes, i've checked and the data is now showing as it should.  Thanks
