### ISSUE TITLE
Use divergent colorscheme for choropleth maps

### ISSUE THREAD

**Issue by jamesscottbrown** [ebmdatalab/openprescribing#347]
Currently, the choropleth maps displayed on ``analyse`` pages are coloured using a categorical scale: rather than colors varying continuously, all CCGs in the same quintile [are assigned](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/media/js/src/map.js#L207) the same color.

The maps would be easier to interpret if a divergent color scheme were used, highlighting values that deviate significantly from the mean in either direction. 

## Example

Consider two antipsychotics, [Zuclopenthixol Acetate](https://openprescribing.net/chemical/040201010/) and [Pericyazine](https://openprescribing.net/chemical/0402010P0/), both of which are used almost exclusively in a small number of CCGs.

### Current color scheme
With the current color scheme, it is hard to tell anything about how prescriptions for either drug are distributed geographically. 

It's difficult to answer the question of how many CCGs prescribe pericyazine at a high level, as many CCGs are assigned the color corresponding to the broad range ``2.29-247.36``.

The map for [zuclopenthixol acetate](https://openprescribing.net/analyse/#org=CCG&numIds=040201010&denomIds=4.2.1&selectedTab=map) has no color variation at all, in the color scale equivalent of the radius scale bug #1.

![pericyazine](https://cloud.githubusercontent.com/assets/338833/23707227/7cbdb434-0409-11e7-9dc4-90b8a4795e1d.png)
![za](https://cloud.githubusercontent.com/assets/338833/23707228/7ee96e6a-0409-11e7-8bf8-e6c55ce16c45.png)

### Divergent color scheme

Re-plottting in R with a divergent color scheme makes the actual pattern of use clear: pericyazine is restricted to a cluster around Norfolk, whereas zuclopenthixol acetate is used at a few isolated CCGs. For convenience, these plots show raw prescription counts (without normalising by dividing by total antipschotic use), but the pattern is broadly the same.

![pericyazine-map1](https://cloud.githubusercontent.com/assets/338833/23706984/68229428-0408-11e7-82a6-b6bf79e5c7c8.png)

![zuclopenthixol_acetate-map1](https://cloud.githubusercontent.com/assets/338833/23708586/52af2966-040e-11e7-8e13-3b66b1e13b55.png)

**Comment by sebbacon** [comment]
## Colour scheme

I agree that a divergent colour scheme may be an improvement.

Here's what the Pericyazine one would look like:

![image](https://cloud.githubusercontent.com/assets/211271/23751621/095a8230-04ca-11e7-9061-e08e2d28a727.png)

## Category discrimination

The issue about the Pericyazine cluster in Norwich not being apparent is not related to the colour scheme.  It's because we classify the values using quintiles.

Upping this to deciles improves discrimination somewhat:

![image](https://cloud.githubusercontent.com/assets/211271/23751248/60d1fae0-04c8-11e7-9874-81ad8430254b.png)

Using equidistant bins, as you did, brings out the anomaly in Norwich:

![image](https://cloud.githubusercontent.com/assets/211271/23751209/2b57a82e-04c8-11e7-897b-96c6856654d8.png)

However, this is at the cost of losing some discrimination in the mid-levels. In this example, where the distribution of values is highly skewed, the mid-level discrimination is meaningless, but in more normal distributions, using quantiles has the effect of increasing the discrimination across all categories.

Looking at such an example (the [Rosuvastatin example linked from the analyse page](https://openprescribing.net/analyse/#org=CCG&numIds=0212000AA&denomIds=2.12&selectedTab=map)), it seems to me that using quantiles doesn't offer any great advantage over equidistant bins (we can also use k-means to cluster which gives similar results):

Using quantiles:

![image](https://cloud.githubusercontent.com/assets/211271/23752213/4bd1a880-04cc-11e7-97ed-888f79a53851.png)

Using equidistant limits:
![image](https://cloud.githubusercontent.com/assets/211271/23752226/5ad23822-04cc-11e7-9ddb-77cf4f022c95.png)

Using k-means clustering:
![image](https://cloud.githubusercontent.com/assets/211271/23752246/6ea40f42-04cc-11e7-9b2f-0248f659db31.png)

## Two-bin anomaly

As you noted, zuclopenthixol acetate example is a different bug affecting cases where there are only two classes of data, which we can easily fix.

**Comment by jamesscottbrown** [comment]
I meant to suggest using a colorscheme that is both diverging and continuous, rather than the current scheme, which is both sequential and semgmented/quantized/binned. 

You are correct that the invisibility of the Norwich pericyazine cluser is due to the binning: I should have been more precise and referred to the 'colormap', to also include the binning process.

As you show, increasing the number of bins helps to improve discrimination. An alternative is to make the color scale continuous. This has the potential disadvantage that it might make it harder for people to read the value for a particular CCG off the scale, but they can get this directly from the tooltip.

If you stick with a binned colormap, I think that constant-sized bins are preferable to variably-sized bins (whether determined by quantiles or k-means):

* in very skewed cases like Norwich pericyazine they show the anomaly much more clearly than do quantile based bins 
* the increase in mid-level discrimination in more typical cases seems to be only slight (based on the Rousavastatin example you show), and small differences from the mean are generally relatively uninteresting anyway
* they have less potential for confusion, as viewers can't be misled by assuming that bins are constant-width

**Comment by sebbacon** [comment]
I see what you mean. Yes, I think that could make sense. Here are some before/after screenshots.

![image](https://cloud.githubusercontent.com/assets/211271/23798453/a65941b6-059c-11e7-9b1e-f54e6d30cea2.png)
![image](https://cloud.githubusercontent.com/assets/211271/23798470/b4e981be-059c-11e7-80ee-2653a5ed15c6.png)

-----

![image](https://cloud.githubusercontent.com/assets/211271/23798488/d0bc016e-059c-11e7-9bcb-1dab247ed7ca.png)

![image](https://cloud.githubusercontent.com/assets/211271/23798503/e20dd99c-059c-11e7-8a58-d7da7d0a6093.png)
