### ISSUE TITLE
Is there anything interesting about rx which aren't allocated to practices?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#349]
When a prescription can't be allocated to a practice by BSA, but it can be allocated to a CCG, it is recorded as `UNSPECIFIED PRACTICE`.

This data is available in the new data source we're going to ingest (q.v. issue #282) and we've agreed to drop it on the grounds it's not actionable.

Before we forget about it, just in case there's some kind of interesting pattern, here is a quick comparison between rx which are unspecified versus specified.

[This BigQuery SQL](https://gist.github.com/sebbacon/ac515a04507819659d2e91b15859fdce) sorts prescriptions for all unspecified practices by total items, and adds a `rank` column based on this. It then compares the `rank` with those for specified practices, filtering for "interesting" ones. 

These are items which are considerably more likely to end up against an unspecified rather than specified code:

![image](https://cloud.githubusercontent.com/assets/211271/23743407/694e266e-04a8-11e7-9fe3-1ec430a2bebb.png)

A tweak of the same query shows those items which are considerably more likely to end up allocated to a specific practice:

![image](https://cloud.githubusercontent.com/assets/211271/23743487/b4184580-04a8-11e7-8032-88dd36b44d5e.png)

And these are items which are *never* allocated to an unspecified practice:

![image](https://cloud.githubusercontent.com/assets/211271/23743556/f554a836-04a8-11e7-9b5a-9c91c9f29399.png)

**Comment by richiecroker** [comment]
The data is probably because of non-medical FP10 prescribing.  Nurses working for different practices (e.g. district nurses, health visitors etc) will often have to write in the practice code manually on the prescription.  Sometimes they will write this incorrectly, and one of two things will happen.  If they happen to write an code for another practice (within the CCG or not) the costs will get misallocated to them.  Sometimes CCGs will find this and will have to bill the correct CCG (this is also in the case of GPs who have moved but the systems haven't followed them correctly).  If the code is not for an existing practice, then it will go to the prescribers "home" CCG under a %998 code.

Note:  NHSBSA never correct the data when it's found to be misallocated.
