### ISSUE TITLE
Introduce mobile testing

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#371]
We've invested a fair amount of resources in supporting IE8 (for which there are some outstanding issues, see issue #372).

But significantly more people use mobile devices (17% on Safari/iOS, 6% on Chrome/Android). Use [Appium on Saucelabs](https://saucelabs.com/automated_testing/ios-app-testing) to run some tests.

On the other hand, if we restrict to (apparently) NHS visits, we find nearly 100% on Windows, with 39% on IE10, 30% on Chrome, and 9% on IE8.

**Comment by sebbacon** [comment]
Update on stats:

* IE8 is the second most popular IE with 1.18% of sessions overall. On its own this would make it hard to justify the effort of supporting it;
* However, it is the third most used browser in "NHS" sessions at 5.92% -- including IE9 too, that's nearly 9% of that traffic.  (Health warning: we're not exactly sure what "NHS network provider" means in the context of Google Analytics).
* If you look at people who interact with the website via email alerts (this includes emails being forwarded around, and people opening emails but not necessarily going to the website) then IE <= 9 is at about 3.5%

I would take the final measure with a pinch of salt because I think it may include HTML renderers within the email client. However, the second measure rings true.

That said, it's still diminishing returns actively supporting IE8/9 and gracefully removing functionality is probably the way to go.

**Comment by brianmackenna** [comment]
I'd support this as well and we should write a blog explaining why we are doing it (if it hasn't been done already). And also why people should be using newer browsers, with links on how to upgrade.

As regards IE8/9 on NHS computers. My last NHS computer had IE10 or 11 as the default but also had up to date chrome and firefox. A lot of my colleagues just used the default that popped up so this might be what is happening. I actually had to roll my IE back to (I think) 8 in order to run certain programmes. I'm pretty sure it was ePACT1  so a lot of Meds Opt people would've had this setup.
