### ISSUE TITLE
Add ability to subscribe to ICB level monthly email alerts and price concession alerts

### ISSUE THREAD

**Issue by chrisjwood16** [ebmdatalab/openprescribing#3725]
Discussed with @richiecroker earlier. With the establishment of ICBs, user requirements for email alerts is likely to change.

It currently does not appear to be possible to subscribe to monthly email alerts or price concession alerts at the ICB level (currently can be done at SICBL, PCN level and practice level).

Where an ICB is made up a single SICBL, the SICBL data will be the same as the ICB data. However a number of ICBs are made up of multiple SICBLs (e.g. NHS North East and North Cumbria Integrated Care Board which is made up of 8 SICBLs) - it is likely some users will want to receive an ICB overview (perhaps in addition to SICBL alerts they may already be subscribed to).

I think this should just be an additional option users can add. No need to change existing SICBL subscriptions to ICB subscriptions etc.

**Comment by evansd** [comment]
I don't this will be _too_ bad. Probably a day's work, maybe a bit more. I anticipate the eventual diff will be quite small, but most of the time will be spent getting to grips (again) with how this all works.

Fortunately, most of the groundwork was implemented in this PR which also provides something of a template for the changes needed:
 * https://github.com/ebmdatalab/openprescribing/pull/2443

Although also note the fix and test that was added here in order to get it actually working:
 * https://github.com/ebmdatalab/openprescribing/pull/2468
