### ISSUE TITLE
Low end of colour scale in maps is wrong

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#426]
![image](https://cloud.githubusercontent.com/assets/211271/25795063/8f7f96fe-33cb-11e7-81e3-01c263f8f91d.png)

The lowest CCG for [this map](https://openprescribing.net/analyse/#org=CCG&orgIds=99P&numIds=120101050&denomIds=12.1&selectedTab=map) doesn't have the colour suggested to be associated with that prescribing rate (dark blue) by the key at bottom right.

**Comment by richiecroker** [comment]
![image](https://cloud.githubusercontent.com/assets/18683239/26312516/c8fb6ee6-3eff-11e7-8c56-49ae45851fa5.png)

Another example where lowest CCG doesn't have the colour

**Comment by HelenCEBM** [comment]
Here is another one. This does seem to be a bit hit and miss. 
![image](https://user-images.githubusercontent.com/24392156/29572505-77bc93f0-8754-11e7-8371-61f831876b14.png)

**Comment by inglesp** [comment]
@richiecroker, @HelenCEBM: in each case, could you include the URL of the page where you took the screenshot?

**Comment by inglesp** [comment]
I have a fix for this in #565.  However, I'm not sure it's the right fix.

Here's a screenshot of the same map as https://github.com/ebmdatalab/openprescribing/issues/426#issue-226965866.

![image](https://user-images.githubusercontent.com/28734/29604054-28070586-87de-11e7-8119-4b4aaa1f23b5.png)

You'll see that the colour bar now just contains the colours on the map, and the high and low numbers on the colour bar correspond to the highest and lowest values on the map.

However, zooming out shows that most of the map is red.  That is, we're not using the full spectrum of colours available to us.

![image](https://user-images.githubusercontent.com/28734/29604352-20a41e36-87df-11e7-8342-e889e00750b5.png)

This is because (I think) if the value on the map are in the range 800 - 1000, the thing that colours the map thinks that it needs to find colours for values in the range 0 - 1000, and so the colours that are used for 0 - 800 are never displayed.  I may have missed a previous discussion of this where it was decided that this was the right approach.

Here's the same map, but where we use the full spectrum of colours:

![image](https://user-images.githubusercontent.com/28734/29604800-8e111e64-87e0-11e7-8ed2-a34c499d74ad.png)

Thoughts?

**Comment by inglesp** [comment]
After discussion in Slack, I'll merge and deploy #565 which changes the colours in the key to match the colours on the map.

#566 changes the colours on the map (and in the scale!) so that the full range of colours is used.

We've also discussed using the standard deviation of each value to choose the colour.  I've spent a little bit of time looking at this, but I think it'll take upwards of half a day to implement this.

We also talked about allowing a user to toggle which colour scheme is used.

**Comment by sebbacon** [comment]
I consider this issue closed! The question of better ways of binning the data is something I'll leave until someone with an important use case begs us for it.

**Comment by sebbacon** [comment]
Thought this had been merged. Reopening until it has been.

**Comment by HelenCEBM** [comment]
@inglesp can this now be closed?
