### ISSUE TITLE
BrowserStack (functional) tests are failing in CI

### ISSUE THREAD

**Issue by benbc** [ebmdatalab/openprescribing#4286]

**Comment by benbc** [comment]
@richiecroker has reported that deploying OP previews is failing. The failures are visible in the `#tech-noise` Slack channel from 11.44 today (Mon 4 Sep).

Most or all OP PRs have been failing for around three weeks. There seem to be a variety of different reasons for these failures -- I don't know if they might all have the same underlying cause, or if there is a coincidence of problems.

The Clininical Informatics team are blocked from doing most of their work while this problem persists.

**Comment by evansd** [comment]
On 2023-08-16 we removed Seb's personal gmail address from being the owner of our Browserstack account (see [thread](https://bennettoxford.slack.com/archives/C03FB777L1M/p1692016636724579)). We confirmed that the functional tests still ran correctly, however we didn't realise that our account had lost its open-source status and corresponding free runtime minutes.

Now all our functional tests fail with:
```
selenium.common.exceptions.WebDriverException: Message: Automate testing time expired.
```

As a short-term measure I have removed these tests from the list of required checks. We very rarely touch the UI these days so in the short term this is not particularly risky.

I'll also investigate what we need to do to restore our account status.
```

**Comment by evansd** [comment]
Support replied very quickly saying that, as far as they could see, we _did_ see have the open-source plan and asking if we could send some screenshots of account settings and error messages. I replied with the requested information but have not yet heard back.

This does make me wonder though, whether I've been mislead by a coincidence of timing. Seb's account was removed at approx 13:50 GMT on 2023-08-16 but the last successful test run was at 12:26 GMT on 2023-08-21:
https://github.com/ebmdatalab/openprescribing/actions/runs/5926204559

And the first failure was 13:00 GMT on 2023-08-21:
https://github.com/ebmdatalab/openprescribing/actions/runs/5926578538

It's possible that was just the point at which we ran out of free testing time, but I think that's unlikely because the _all_ the browser tests in that second run failed and I'd have expected it to have got part way through the tests before running out of time.

So maybe something else changed which means our credentials aren't being recognised properly or something?

**Comment by evansd** [comment]
On Wed 6 September BrowserStack support asked me for the username of the account the tests were being run under. I replied immediately with the details of the `openprescribing` service account. I have not heard back from them, however as of this morning (11 September) the functional tests seem to be running successfully again.

We'll see how long that lasts.

**Comment by evansd** [comment]
I noticed the functional tests were still failing for Dependabot PRs and realised that they have separately configured BrowserStack credentials so have updated those too.

Support replied to me saying that they see from the logs that tests are running now and asking if it's an intermittent problem. I get the impression from this that they haven't explicitly changed anything on their end.

**Comment by evansd** [comment]
This appears to be resolved, though still don't know exactly what the original problem was. But BrowserStack support have closed their ticket, and so shall I.

**Comment by inglesp** [comment]
Thanks for digging into this.
