### ISSUE TITLE
Direct linking to measures from email alerts is broken

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#4588]
A link like this (https://openprescribing.net/practice/J81010/measures/?tags=cost#lpherbal) (note the anchor fragment) is configured to scroll to the measure and highlight it, like this:

![image](https://github.com/ebmdatalab/openprescribing/assets/211271/6d4789ed-53e4-4ec8-9241-24d6e4c558ac)

However, this doesn't usually work when linked from the email alerts. Here's an example link from an alert:

https://openprescribing.net/practice/J81010/measures/?utm_medium=email&utm_campaign=monthly+alert+2024-01-23&utm_source=dashboard-alerts&utm_content=%2Femail%2Fmonthly+alert+2024-01-23%2Fdashboard-alerts%2F1502#lpherbal

(in passing, I think we don't use google analytics any more? So those tracking tags are redundant?)

**Comment by evansd** [comment]
I don't think the issue here is quite as described. The problem is that the specified measure does not appear on the linked page.

Possibly this is because it is not tagged as a "core" measure?
https://github.com/ebmdatalab/openprescribing/blob/840ca40d58fad7008ea411307eb443268cf17e80/openprescribing/measures/definitions/lpherbal.json#L30-L34

I thought that only "core" measures got included in email alerts, but maybe I've misunderstood/misremembered.

Changing the specified measure to one that _does_ exist on the page demonstrates that the measure highlighting works even in the presence of the UTM parameters:
https://openprescribing.net/practice/J81010/measures/?utm_medium=email&utm_campaign=monthly+alert+2024-01-23&utm_source=dashboard-alerts&utm_content=%2Femail%2Fmonthly+alert+2024-01-23%2Fdashboard-alerts%2F1502#statinintensity

Regarding what we currently use for stats, I think we're using _both_ Google Analytics and Plausible. Certainly we're still loading the GA javascript.
