### ISSUE TITLE
Consider time series rather than point-in-time snapshot for PPU prices

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#466]
@HelenCEBM said:

> concerned that we are only showing a single-month snapshot and it might be useful if users can see the changes in price over time for each brand (as per some of the charts Rich has shared in Slack) before they dive in and switch to a drug whose price is actually on the rise. They may prefer to select one that’s currently not the cheapest but has been consistently reducing

**Comment by sebbacon** [comment]
I like this idea, but concerned about the details and/or implementation time!

When the x-axis is time, what is the y-axis?  Are we talking about a single line chart with mean PPU for each brand + generic? Or something else? 

If the former, the problem of rarely-prescribed but cheap brands may be more acute, and we will lose the current relationship of the y-axis to the quantity of prescribing. Neither of which are necessarily big problems, but may be!

**Comment by lmfrench** [comment]
Could we have a slider on the current graph similar to how we do on the spine charts on the analyse page?

**Comment by richiecroker** [comment]
It will be an inherent problem whatever we do.  The biggest issue we have with this data is timelag.  

Take venlafaxine MR 75mg capsules:
![image](https://user-images.githubusercontent.com/18683239/27532651-e021acce-5a58-11e7-8e96-1a8298e7a63e.png)

In March (the latest month we have data for) venlafaxine MR generic is showing as expensive.  It reduced significantly in price in April (by changing the Category C status from _Efexor_ to _Vensir_.  Consequently most of the savings will be gone, and what was the most expensive becomes the cheapest.

I'm not sure, short of monitoring the Drug Tariff separately and modifying the data accordingly, we can do.  I don't think that adding more than one month's data will fix it.

**Comment by HelenCEBM** [comment]
I was imagining a line chart of PPU over time for each brand and generic, like this example rich made before, but in addition to the current chart, e.g. "click here to see how these brands have changed in price over time".
![image](https://user-images.githubusercontent.com/24392156/27539050-c9a06480-5a72-11e7-9038-0cc2b5a4e13c.png)

However it's not very pretty when there are many brands, and would need a bit of thinking about. And as RIch says, the changes in price since then are more relevant, but harder to keep track of.  Still I think it's useful to see how much the prices can change... Perhaps a feature to add later? Or we could show one as an example in the FAQ / walkthrough (I think Cerelle was a great one).

**Comment by jamesscottbrown** [comment]
@HelenCEBM It looks like several products have constant prices. You could try reducing the opacity these lines, to reduce clutter and focus attention on the price changes.

**Comment by richiecroker** [comment]
We think we'll just describe and illustrate the issue of changing DT prices in our walkthrough.
