### ISSUE TITLE
How much do we need to shout about potential licensing issues?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#468]
For example, until the licence is up (soon), pregabalin can only be prescribed generically for epilepsy, not pain.

@HelenCEBM said:

>  We should keep an eye out for any other additional use licences! Would be bad to be seen to be encouraging people to breach licences...

There are some not-very-obvious notes about such things in the "Limitations" section of the savings-table-page, which could be extended, linked to from the top, etc.

![image](https://user-images.githubusercontent.com/211271/27533086-3f330144-5a5a-11e7-878e-bfefd7924b80.png)

This links in general to the meta question mentioned in #462, viz how to square not wanting to give the illusion of accurate guidance when it's impossible to do so with wanting to show we're clueful enough to be a bit helpful in interpretation.

**Comment by richiecroker** [comment]
@HelenCEBM said:
> Would be bad to be seen to be encouraging people to breach licences...

I don't think we do.  That's why i've been very clear (including in the paper) that we are only showing where there is prescribing at a cheaper cost, not recommending different products.

BTW, it's not just us.  To use the same example as in the other thread, where the price of venlafaxine 75mg MR caps was based on Efexor and is now Vensir, Efexor has a license for GAD, whereas Vensir has a "skinny label" and doesn't.

**Comment by HelenCEBM** [comment]
Although we're not actually recommending switching, I think people will see it that way and I think it is safer to be a bit more explicit about licensing/legal issues so that people can't fall too easily into the trap. I imagine doctors would be happy with judging the output in the context of patient care but perhaps less aware of this kind of issue. I like what Seb suggested above, expanding the limitations and linking to it from the top.
