### ISSUE TITLE
Categorise and discuss achievable savings

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#492]
Rich [has assessed](https://docs.google.com/spreadsheets/d/1yn77pttJbBlFI5iLZJIryThggv5D_9c1DCjPKtfQGRo/edit#gid=0) the top 10 savings for 10 random practices, to inform discussions / decisions about achievability.

### Impossible savings (12% of the savings by cost):

* Starch powder often appears as a saving, but there are pack size issues (per the discussion at https://github.com/ebmdatalab/price-per-dose/issues/12 which I was hoping to close off with NHS BSA). If the sachet issue is hard to pin down it may be best to exclude all of `1902%` from our analysis (Other Drugs And Preparations > Base/Dil/Susp Agents/Stabilisers).
* Nicotine inhalers (`0410020B0AABZBZ`), Generic Aveeno cream ( `130201000AAA8A8`) and Isopropyl myristate 15% / Liquid paraffin 15% gel (`130201000AACACA`) have pack sizes where the smallest pack sizes are considerably cheaper than the largers. For example, Nicotine inhalers are prescribed in ranges from 4 to 200, and the per item cost ranges from 67p to £1.07.  The issue is discussed in [this ticket](https://github.com/ebmdatalab/price-per-dose/issues/2) (look for "Type 1").  We could manually exclude these specific examples, or we could attempt it statistically by looking for items that are in the DT, and which have large PPU ranges within a branded presentation and are known to have several pack sizes. 
([start of such a query here](https://gist.github.com/sebbacon/9d4510e24913a4468aeaa9be193ab11e))
* Tacrolimus 5mg/5ml oral suspension (`0802020T0AAALAL`) and Mycophenolate mofetil 500mg tablets (`0802010M0AAABAB`) have bioequivalence issues

### Unclear (38% of savings by cost):
* Specials and NP8 drugs. Drugs where the pharmacist has much discretion

### Possible (11% of the savings)
* Test strips where the switch also requires a new meter
* Things like Lamotrigine, which has bioequivalence issues

**Comment by richiecroker** [comment]
The starch powder pack size issue is the same as the others - it comes in different packs, where *usually* the bigger the pack, the cheaper the PPU.

This actually used to be the case with many more things (including paracetamol!), but is now fairly limited.

It's yet another area where the pharmacist has the power, rather than the CCG or practice, even when relatively nonsensical - e.g. if a GP prescribes 2.5kg of Aveeno, the pharmacist can give and endorse 25x100g, as opposed to 5x500g.  Even if the GP prescribes 5x500g, the pharmacist can give 25x100g.  ETP removes even the ability to state this.

Re the "possible" class: 

BGTS: no less achievable than a number of other switches (it's been done across the country), but requires more effort, similar to the inhaler switches, as you ideally need face to face discussion with the pt about new devices.

Lamotrigine: only a [category 2 bioequivalence risk ](https://www.gov.uk/drug-safety-update/antiepileptic-drugs-new-advice-on-switching-between-different-manufacturers-products-for-a-particular-drug) for this, but I suspect the pts still on Lamictal (branded lamotrigine) are on it because they don't want to change.  That said, current Lamictal proportions ranges from nothing to nearly 40%, so there is obviously an explained level of variation:
![image](https://user-images.githubusercontent.com/18683239/28069684-3d38a512-6642-11e7-904a-d90f3f4c0762.png)

**Comment by sebbacon** [comment]
I'm not sure you're right about Starch Powder - I was thinking of [this analysis](https://github.com/ebmdatalab/tariff-data/blob/master/Drug%20price%20variance.ipynb#Where-are-there-big-savings?) from ages ago, which suggests ThickenUp is either recorded by gram or by packet. Though the outcome is similar (discontinuous price points).

I think we should do all we can to remove impossible savings, and add commentary about where savings may be tricky.

For the former, we can either exclude specific codes as we find them, or attempt to identify products that exhibit this property from dm&d etc.  The former is easier but we will certainly have missed some. The latter is hard to quantify without playing a lot with the data. I suspect it would be 2 or 3 days of work for someone with SQL skills, but there's a risk that we find it's not possible to identify such products reliably. It may be worth trying if it means we can reduce practice-level false positives by around 10%?

In terms of highlighting potential issues, as we've discussed previously, I think the general approach should be an exhaustive FAQ, with links to specific sections where we can automatically tell something might be an issue (viz. NP8, Specials, Imports, non-bioequivalence), test strips needing devices.

Is there a way we can similarly highlight things that commonly have rebates? I presume these are commercial secrets!

**Comment by richiecroker** [comment]
I got the calculator out for thick and easy list prices yesterday, there's definitely a difference in price per gram.

CCGs should provide a list of rebates under FoI. We have a list on our website, although without discount terms.  It's not just inhalers, we have several tablets as rebate as well.  Even so, it doesn't mean that, even with a rebate, one inhaler is now cheaper. But when you add in hidden cost of change it's not so clear cut.

**Comment by HelenCEBM** [comment]
some rebate info from previous FOIs: https://www.whatdotheyknow.com/search/ccg%20rebate/all

**Comment by sebbacon** [comment]
In a sample of the first 20 CCGs that came up in the FOI list linked to by Helen, more than 50% had rebates on Zoladex or Seretide.  

![image](https://user-images.githubusercontent.com/211271/28271021-61f5d1c4-6aff-11e7-9a1b-3f73f02a11fe.png)

(as an aside, the range of rebates was interestingly broad - I wonder if "number of rebates" correlates with anything else):

![image](https://user-images.githubusercontent.com/211271/28272532-b41b26da-6b03-11e7-9dec-c41549a97783.png)

Of the 11 products which had at least 25% of CCGs signed up, there were 6 that come up with non-trivial possible savings in our current analysis: GlucoRx (£3.9m), Seretide (£2.5m), Symbicort (£1.6m), Mezolar (£870k); Glucophage (£930k); Ebesque (£969k).  If extrapolated across the whole population this would be about £3.8m of project savings that in practice may not be application due to the availability of rebates - i.e. about 7% of the total savings we have projected may be subject to rebates (these were categorised as *achievable* in Rich's spreadsheet).

I'd suggest we give GlucoRx, Symbicort and Seretide as our examples of rebates on the website; I guess for the paper we just need to ensure it's discussed somewhere.  We could actively flag (e.g. asterisk) the above items when they appear, though this has the disadvantage of needing keeping up to date, so I don't think it's a good idea.

**Comment by richiecroker** [comment]
Rebates is probably an area that is just too complicated to get into for purposes other than, as you say, mentioning it in the paper as a possible reason why cost reductions are not likely to occur (and, possibly yet another reason why the system is broken).

In my own experience rebates exist in two or three forms.

Firstly there's the type of rebate which may make the CCG pause in actively switching brands, as the difference in money between the rebated price and the cheaper brand is now not worth investing time into, when we could be doing something else.

Secondly there's the type of rebate where the brand with the rebate on offer is already the cheapest brand available, and therefore the rebate *may* mean that the CCG choose that brand over another, seemingly identically priced choice.

Thirdly, there's the "it's there so we may as well have it" type.  This is where CCGs may sign up to a rebate for a brand that is not prescribed, but it's there so the rebate might as well be taken.  We've had one brand where the annual rebate has been under £100!

**Comment by HelenCEBM** [comment]
Back to pack sizes, here's a BigQuery script to pick up branded items which vary in price and also have PPU savings (though for some, the savings potential may be because the generic or another brand is cheaper). I've joined to DMD as well which shows that all of the resulting list of drugs can also have special containers or broken bulk issues. However some of them are genuine pack size issues, see [results and some spot checks](https://docs.google.com/spreadsheets/d/1g_w8cnRu0pnTjZr5UWbrScK2avHniOnROSUvrZ3rZWc/edit#gid=796917063). However it doesn't seem like an extensive list and suspect we are missing some...

```-- investigating price-per-unit differences caused by different pack sizes
WITH a AS (
SELECT 
  CONCAT(SUBSTR(presentation_code,1,9),'AA',SUBSTR(presentation_code,12,4)) AS generic_code,
  presentation_code AS BNF_code, 
  MAX(round(IEEE_DIVIDE(net_cost,Quantity),2)) AS max_ppu, 
  MIN(round(IEEE_DIVIDE(net_cost,Quantity),2)) AS min_ppu
FROM ebmdatalab.tmp_eu.prescribing_2017_03_01 
WHERE 
  SUBSTR(presentation_code,10,2) != 'AA' -- exclude generics
  AND quantity>0
  AND SUBSTR(presentation_code,1,2) < '16'
GROUP BY BNF_code

ORDER BY BNF_code)


--join to dmd and ppu savings:
SELECT 
  CASE WHEN p.bnf_code IS NOT NULL THEN 1 ELSE 0 END AS ppu_saving, 
  a.generic_code, 
  a.bnf_code,
  c.presentation, 
  non_availcd, 
  avail_restrictcd, 
  CASE WHEN flag_broken_bulk= 't' or flag_special_containers	= true then 1 else 0 end as sp_cont_brok_bulk,
  max_ppu, 
  min_ppu, 
  round(max_ppu-min_ppu,2) AS difference
FROM a
--INNER JOIN ebmdatalab.helen.drugs_w_multipe_pack_sizes b ON string_field_0 = CONCAT(SUBSTR(bnf_code,1,9),'AA',SUBSTR(bnf_code,12,4)) -- this may be missing some
LEFT JOIN ebmdatalab.hscic.bnf c on a.bnf_code = c.presentation_code
LEFT JOIN ebmdatalab.hscic.dmd d on a.bnf_code = d.bnf_code 
INNER JOIN (SELECT DISTINCT bnf_code FROM ebmdatalab.hscic.ppu_savings) p on p.bnf_code = a.generic_code
WHERE max_ppu-min_ppu > 0.0 AND d.product_type > '1' AND d.concept_class > '1' AND flag_imported = 'f' and tariff_category != 'null'
ORDER BY generic_code, difference desc```
