### ISSUE TITLE
Closed and Dormant practices

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#526]
This issue is a roundup of several other issues

#522 #513 #408 #479 #401 #215

**Comment by HelenCEBM** [comment]
Can we add words to the effect of `Current status: "Dormant" / "Closed"` to the practice dashboard pages? Probably better not to include this if the status is Active though.

I (may be wrong! but) imagine this not to be too difficult since it's listed in the practice dataset alongside the practice type... Surely this will be helpful to users, as well as ourselves when investigating weird practices (I seem to do that a lot), and stop people needing to contact us about closures/mergers of practices that we can't fix.

**Comment by sebbacon** [comment]
Wrapped up into #891
