### ISSUE TITLE
Fix cost-saving measures

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/openprescribing#556]
There is a problem with the way price savings are being calculated at GP Practice level for some(?) of our cost-saving measures

Example: Keppra
A user got in touch with us to say that on the [GP Practice dashboard](https://openprescribing.net/practice/Y02811/) the keppra measure says 

> 'This practice was at the **32nd percentile** on average across the past 6 months. If it had prescribed in line with the median, this practice would have **spent £98.36 less** over the past 6 months. If it had prescribed in line with the best 10%, it would have spent £330.67 less.'

If you look at Keppra across the whole of the CCG, some practices below the median have the correct text ("this practice has saved the NHS") but others have the incorrect text ("this practice would have spent X less")

When looking at this, I noticed that the deciles on the practice pages aren't the same as the deciles we use on the CCG pages. This might be what is causing the problem. The median for Keppra at CCG level in May is 12.2%, and at practice dashboard level it is 6.7%.

**Comment by lmfrench** [comment]
Other measures with this problem:
Statins: https://openprescribing.net/ccg/08A/statins/ - see G83063: DR BPC PEIRIS' PRACTICE 'This practice was at the 33rd percentile on average across the past 6 months. If it had prescribed in line with the median, this practice would have spent £71.61 less over the past 6 months.'

ARBs: https://openprescribing.net/ccg/08A/arb/ G83015: ELTHAM PALACE PMS'This practice was at the 41st percentile on average across the past 6 months. If it had prescribed in line with the median, this practice would have spent £14.55 less over the past 6 months.'

Quetiapine:  https://openprescribing.net/ccg/08A/quetiapine/  Y02974: AT MEDICS This practice was at the 46th percentile on average across the past 6 months. If it had prescribed in line with the median, this practice would have spent £259.06 less over the past 6 months.

**Comment by sebbacon** [comment]
I assume the user is expecting that a mean prescribing at the 33rd percentile means they are on average saving money.

However, this is not necessarily the case.  Take this example:

![image](https://user-images.githubusercontent.com/211271/30166292-c98334ae-93da-11e7-9b07-8d580b4546b0.png)

The raw data behind this is:

```sql
127.0.0.1 prescribing@prescribing=> select cost_savings::json->'50' as saving_at_50th, num_quantity, num_cost, denom_quantity, denom_cost, percentile from frontend_measurevalue where practice_id = 'G84028' and measure_id = 'keppra' and month >= '2017-01-01' order by month;
┌────────────────────┬──────────────┬───────────┬────────────────┬────────────┬──────────────────┐
│   saving_at_50th   │ num_quantity │ num_cost  │ denom_quantity │ denom_cost │    percentile    │
├────────────────────┼──────────────┼───────────┼────────────────┼────────────┼──────────────────┤
│ -86.49003417816812 │            ¤ │         ¤ │           1652 │    82.8436 │                0 │
│ 297.46954105163456 │          720 │ 390.53967 │           2068 │  454.55308 │ 86.6201995353287 │
│ -69.8367472151917  │            ¤ │         ¤ │           1268 │    62.8564 │                0 │
│ 126.98421699499684 │          240 │ 182.65712 │           1036 │  222.41641 │ 77.0973499931347 │
│ 32.56947132132193  │          120 │  91.44697 │           1100 │   140.0423 │ 58.4604810996564 │
│ 1.2742207791714009 │          120 │  91.36943 │           1644 │  171.38505 │ 50.1859760297562 │
└────────────────────┴──────────────┴───────────┴────────────────┴────────────┴──────────────────┘

```
Here we can see that the mean percentile is indeed 45. The issue is essentially that over the last 6 months, the area above the median is much larger than the area below the median for this practice.

I agree this is confusing but I'm not currently feeling inspired as to the solution!

(To address the point about CCG deciles and practice deciles being different, we would expect this because CCGs are aggregations of different groups of practices, so the aggregated proportions will vary differently from the individual ones)

**Comment by sebbacon** [comment]
Possible solutions from team discussion:

1. Remove "this practice was at the Nth percentile" text. The original reason for its inclusion was to provide an explanation for the ranking. But this is fairly intuitive anyway and people can get the percentile from the graphs. Another advantage of this approach is less text == good.
2. Smooth total rolling six month data to produce percentile, rather than mean. This would then produce a metric in line with the six month savings figure.

I prefer (1) as it is simpler.
