### ISSUE TITLE
Import NCSO data monthly

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#599]
Monthly shortage lists are published [here](http://psnc.org.uk/dispensing-supply/supply-chain/generic-shortages/).  We would like the ability to mark any presentation in any given month as in that list, along with its price.

This could be achieved by updating a table, monthly, linked to our dmd tables (see below).

A presentation is defined by the generic name + dose + form + pack size, i.e. the first two columns of that list.

## Relevant resources

* We should probably link this to our the DMD data we import, if possible. An alternative is to link it to BNF codes but the huge difference in naming in the BNF scheme is likely to make this much harder.
  * In our database, the DMD tables are all prefaced `dmd_` (and some but not all have corresponding models in the `dmd` app in `openprescribing`).
  * The entity we'd map with is `dmd_vmpp`, so we could make a table with a foreign key on `dmd_vmpp.vppid` for the NCSO data. The `nm` field should be relatively matchable
* @richiecroker has done some quick analysis by hand and says the majority match very well, and a minority don't - so we should do that a bit more systematically and see if we can fix the misses herustically
  * if not, we need to devise a workflow involving google sheets for someone to (e.g.) copy/paste and fix by hand monthly
* online version of DMD [here](http://dmd.medicines.org.uk/)

Here's a sample query against the db on `largeweb2` illustrating a name match:
```
127.0.0.1 prescribing@prescribing=> select * from dmd_vmpp where nm like '%Terbinafine 250mg tablets%';
┌───────────────────┬─────────┬─────────────────────────────────────┬──────────┬───────────┬────────┬───────────┬────────────┐
│       vppid       │ invalid │                 nm                  │ abbrevnm │   vpid    │ qtyval │ qty_uomcd │ combpackcd │
├───────────────────┼─────────┼─────────────────────────────────────┼──────────┼───────────┼────────┼───────────┼────────────┤
│ 18490211000001108 │       ¤ │ Terbinafine 250mg tablets 8 tablet  │ ¤        │ 324718007 │      8 │ 428673006 │          ¤ │
│ 14755511000001101 │       ¤ │ Terbinafine 250mg tablets 16 tablet │ ¤        │ 324718007 │     16 │ 428673006 │          ¤ │
│  1122811000001109 │       ¤ │ Terbinafine 250mg tablets 28 tablet │ ¤        │ 324718007 │     28 │ 428673006 │          ¤ │
│  1313611000001101 │       ¤ │ Terbinafine 250mg tablets 14 tablet │ ¤        │ 324718007 │     14 │ 428673006 │          ¤ │
└───────────────────┴─────────┴─────────────────────────────────────┴──────────┴───────────┴────────┴───────────┴────────────┘
```

**Comment by richiecroker** [comment]
It's important for this that we get the timing correct.  We have a bit of time between publication of the lists, and the data arriving.  The monthly lists also can (and do) change throughout the month.  Therefore, I would suggest that either pull data from the price concessions site either for the period we are about to upload, or a month ahead, so that there is no delay for the data.

E.g. my preference would be to look to pull September's data now.  

With regard to the naming issue, the minority that didn't were either because a) they no longer have a DM+D code (e.g. co-proxamol), or where for some reason the DM+D has been truncated due to units - e.g. mcg has become microgram.

My other thought would be to refer to the existing data that we've created to pull the relevant codes first.  A lot of the current price concessions have been running for many months, and therefore we may as well only do the work once where we have to.
