### ISSUE TITLE
Analyse page slow to load

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#746]
https://openprescribing.net/analyse/#org=CCG&numIds=0407010F0&denom=nothing takes about 11s to load.  This includes making 4 requests to our API:

* https://openprescribing.net/api/1.0/bnf_code/?format=json&exact=true&q=0407010F0 (280ms)
  * returns data about chemical from BNF (section, type, name, id)
* https://openprescribing.net/api/1.0/spending_by_ccg/?format=json&code=0407010F0 (925ms)
  * returns one record for each CCG for each month, with actual_cost and quantity of drug
* https://openprescribing.net/api/1.0/org_details/?format=json&org_type=ccg&keys=nothing (598ms)
  * returns one record for each CCG for each month, with no information that can't be derived from response to previous request (since denominator is "nothing")
* https://openprescribing.net/api/1.0/org_location/?format=json&org_type=ccg (2909ms)
   * returns geojson data which is only used for map page

There is about 5s before the `org_location` request is made, which from code-reading is presumably from running `setUpData` in chart.js.  On older browsers/older computers, I'd bet this takes significantly longer.

Possible savings:

* only load geojson page when we show the map
* or cache geojson data
* don't make denominator request when denominator is "nothing"
* do work to set up data on the server (in the database?)
* cache all BNF data in browser

(If slowness is not a concern for users, we should close this issue.)

**Comment by sebbacon** [comment]
Slowness isn't a concern for users, at least no-one has ever complained, so it's generally been low-priority and just up to when I feel like having a go to improve performance.

I don't see why geojson data isn't being cached in the browser - that would probably be the most parsimonious next step.

Otherwise I think the rest would only be worth addressing if/when we revisit the whole form as there are several javascripty interdependencies that would be worth refactoring (I've done this incrementally each time I've had to revisit javascript for other reasons).

**Comment by HelenCEBM** [comment]
This doesn't seem overly slow to me when tested just now, and we can address speed issues as part of the wider development
