### ISSUE TITLE
Allow linking to / grouping of related measures

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#849]
For some measures such as overall antibiotic rate and % broad spectrum, it is helpful to view/interpret the two measures in combination; similarly for opioids measures (currently x3).

Could create some grouping or linkage for each of these measures, e.g.
- "see also X" which links directly to the other measure(s). E.g. if on a practice/ccg dashboard, `see also opioid prescribing rate per 1000` could link to [practice_id]/#opioidper1000 to highlight the related measure.
- "see all related measures" linking to a page displaying the group of related measures. However, note that for antibiotics there is a wider group of measures on the same topic, some less closely related than others, so multiple options may be needed.

**Comment by sebbacon** [comment]
See also #882

**Comment by sebbacon** [comment]
#876 I mean

**Comment by sebbacon** [comment]
I think there are also some other issues relating to this that I'd like to gather together before acting.

Agreed @evansd will review existing code first, then we'll return for more discussion as there are a few high-level UI options here.

**Comment by sebbacon** [comment]
Related issues:

* #810 is related insofar as it's a measure we didn't want to appear with other measures, so we tagged it `paper`, and then we link to it explicitly in papers like https://openprescribing.net/ccg/09C/?tags=paper
* #847 is the second instance of us wanting to do this, i.e. a measure that we want to maintain as a living dataset linked to from a paper
* #876 is a bug in the current implementation, which is in any case quite hard-coded and needs further generalisation

As an example of how we might generalise this - there could be a tabbed interface to measures showing "Core measures", "Cost saving measures", "Efficacy measures", "Safety measures", "Measures mentioned in papers".  This would only address Helen's second bullet point in the OP.

**Comment by evansd** [comment]
Also relevant is Helen's categorisation of measures here:
https://docs.google.com/spreadsheets/d/1Yx9_dWnjscN6FNfes5Q3LT2E2yRdYbQVOY1Q-aZRFQw/edit?usp=sharing

**Comment by evansd** [comment]
## Proposed solution (for discussion)

### 1. Switch from JSON to YAML for measure definitions?

YAML has the advantage that it's easier to write for humans e.g. it's not fussy about trailing commas, it supports mutliline strings and comments. Embedding chunks of text (and even HTML) is [very easy](https://en.wikipedia.org/wiki/YAML#Indented_delimiting).

Given that all valid JSON is also valid YAML we wouldn't need to actually change any of the files and no one would be immediately forced to learn a new syntax so it would give us a nice smooth transition from one to the other.

The major disadvantage of YAML is that its parsing complexity makes it hard to guarantee the security of the parsing libs so I wouldn't want to use it on untrusted input. But in this context that's not a concern.


### 2. Tags need some richer metadata attached

At a minimum they need a human-readable name ("NHS Low Priority" vs `lowpriority`) and a description.
It would probably make sense to have this defined in a JSON/YAML file like the measures themselves.


### 3. Each measure should display its tags, which should act as filter links

In the panel for each measure (in all contexts where measures appear) we should display the human readable names for each of the tags that measure has e.g.

> This measure is tagged as: Cost, Easy Improvement

Clicking any of the tag names should filter the measures to just those matching that tag.


### 4. When filtering by tag the tag description should be shown

Like we do for low priority measures currently, but generalised to all tags rather than hardcoded.


### 5. Possibly use a hardcoded subset of tags to define a tabbed interface

We wouldn't want to expose every tag we use as a tab; but it might be nice to have, on the CCG/practice dashboards, a quick way to filter e.g.

> All Core Measures, Cost Saving Measures, Safety Measures ...

### 6. Do we really want/need measures that link to one other specific measure?

Helen initially proposed a "See also X" link for some measures which would jump you to another measure on the page. I'm wondering if point 3 above would fulfil the same need. It would allow you easily to see e.g. all opioid measures together with a single click which might be preferable to being jumped around the page without having the measures next to each other for comparison.

This also solves the problem of having multiple levels of grouping. For instance, we could have an `antibiotics` tag which groups all measures related to antibiotics and then further `antibiotics-whatever` tags which link smaller groups of measure which are closely related.

**Comment by sebbacon** [comment]
Sounds good. One thing to discuss: I wonder if we should take the opportunity to switch to models instead of JSON or yaml

**Comment by brianmackenna** [comment]
I have created a new spreadsheet https://docs.google.com/spreadsheets/d/13MRojwXXd-Cg68ChpyQFqhLpeTta3X6pjUCQj--TXiQ/edit#gid=25649249 to start to group measures together - will require some more discussion

**Comment by evansd** [comment]
Closed in #915
