### ISSUE TITLE
Add pack size as separate column to Drug Tariff download

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openprescribing#923]
Currently the download for DT prices (https://openprescribing.net/api/1.0/tariff/?format=csv) has the following columns:

- concession
- date
- price_pence
- product
- tariff_category
- vmpp

In order to use the download to easily calculate cost changes, it would also be useful to have the pack size.

**Comment by richiecroker** [comment]
I've just downloaded this, but it only shows a pack size where there has been a concession, rather than for all drugs.

e.g.
![image](https://user-images.githubusercontent.com/18683239/42994306-a6e33402-8c05-11e8-9c7a-f9ffb5f278f8.png)

**Comment by evansd** [comment]
When I built this I searched the database schema for "pack size" and the only column I found was on `dmd_ncsoconcession`. Do we have the pack size in the database somewhere for other drugs?

**Comment by sebbacon** [comment]
<*sigh*> it looks like we never included it in the model for some reason:

https://github.com/ebmdatalab/openprescribing/blob/f0e55fad0a6f0518c8d99c4ca4fde9a71316f2e9/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py#L104-L109

**Comment by richiecroker** [comment]
It must be coming from somewhere, as the tariff viewer shows the pack size. VMPP records?
![image](https://user-images.githubusercontent.com/18683239/42998235-6284878c-8c11-11e8-8076-a5dea29a779b.png)

**Comment by sebbacon** [comment]
@richiecroker is right, we can get it straight from dm+d (which is why it's not in our own model), so it should actually be trivial.  We just need to select `dmd_vmpp.qtyval AS pack_size` here:

https://github.com/ebmdatalab/openprescribing/blob/af6b4da8db677d8c6d7e2736877a3f54fce23c10/openprescribing/api/views_spending.py#L320-L326

Probably doesn't need its own ticket after all.

**Comment by evansd** [comment]
Oh I see!

Sorry, I'm so used to seeing Django models as definitive of the database structure, so I was assuming we weren't importing the field.

**Comment by sebbacon** [comment]
Me too, and I wrote that code :-)

The dm+d data doesn't have a full ORM version because the import process converts XML to SQL and runs various conversions that are copied straight from the documentation, which end up with that heavily normalised schema which would, frankly, be a PITA to use via an ORM (in my opinion). 

That said, some of the tables do have an ORM model where they're commonly used in code ([example](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/dmd/models.py#L157)).

**Comment by evansd** [comment]
That's a good idea. I'd definitely be more in favour of code generation than metaprogramming :) If we can piggyback off `inspectdb` than that might be the easiest thing, but I guess we'll need to see what sort of results it gives us.

**Comment by sebbacon** [comment]
My concern, if you map one-to-one with tables, is that you'd end up with unreadable ORM queries - think about the three-dimensional AMPP diamond as a queryset filter?!

The SQL query quoted above is a case in point.

A possible alternative would be to write views on the data that generate somewhat denormalised models each month.

**Comment by evansd** [comment]
There's nothing to stop you making raw SQL queries against tables also represented in the ORM
