### ISSUE TITLE
Tariff search should use VMP/AMP as index key

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#945]
Currently we look up Tariff data via a BNF code.

Tariff data is supplied at the VMPP level, but most BNF codes map to the VMP/AMP level.  When more than one VMPP matches the BNF code, we show them all on the same chart. This is desired behaviour.

However, in [some cases](https://github.com/ebmdatalab/openprescribing/issues/940) BNF codes map directly to VMPP. This means the user won't get to see related items on the same chart.

Therefore, the fix is for the API to accept a VMP as a filter parameter, and pass this from the front end selection widget.

We should perhaps keep the BNF code as a filter parameter because this allows us to cross-link from other places in the website (e.g. price-per-unit would be a good place).

**Comment by evansd** [comment]
@sebbacon Having looked at this a bit I think I'm going to need some more pointers to get started. For instance, the only VMP model we have is in `dmd2` and I'm not sure how this relates to the stuff in `dmd` which is where the tariff data lives.

So the first hurdle is that I don't know what table and column to try to match a VMP against.

**Comment by sebbacon** [comment]
OK, grab me for a chat Monday

**Comment by evansd** [comment]
Note to future self: in the dmd models, VMP is spelled `vpid` and VMPP is spelt `vppid`.

**Comment by evansd** [comment]
This issue is proving hard to replicate. We have [here](https://github.com/ebmdatalab/openprescribing/issues/818#issuecomment-406378604) a list of BNF codes which map to VMPPs, rather than VMPs. However, trying various examples from this in the tariff viewer seems to give a chart showing all the related VMPPs under the same VMP, rather than the single VMPP which the code maps to.

For example:
The code `0206010F0AACJCJ` maps to the 200 dose pack of "Glyceryl trinitrate 400micrograms/dose pump sublingual spray". But the chart below shows both the 180 and 200 dose packs.
https://openprescribing.net/tariff/?codes=0206010F0AACJCJ

@inglesp Is this an issue that somehow got fixed while fixing something else?

**Comment by inglesp** [comment]
Closing, as (a) it's not clear what the problem was, and (b) the implementation will be changed when the new dm+d code is integrated.
