### ISSUE TITLE
ebmbot facilitation of NCSO reconciliation

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#959]
NCSO reconciliation should be done by somebody who knows what they're doing (ie @richiecroker and not me).

@ebmbot should be able to help with that.

**Comment by sebbacon** [comment]
Bumping the priority of this, because @richiecroker has made it repeatedly clear that the timeliness of our alerts is Very Important!

In addition to reconciliation, we should integrate the whole flow into a chatops sequence.

At the moment, if they don't go out, it's hard for Rich to know why, and/or if action from him is required.

I think that *fetching* the data should also be a bot command that can be triggered manually, and the cron job should ideally trigger **via chatops**; automatic reconciliation the same, with errors being reported in slack so people at least know it started and failed; and finally, per the original issue, manual reconciliation should be possible via slack too.

A possible mechanism for reconciliation is something like `op nsco report` which (among other things) would list numbered, unreconciled items; and `op ncso reconcile <unreconciled_id> <vppid>` (with advice to the user to use the DM+D browser to find the vppid).

**Comment by inglesp** [comment]
This is done.
