### ISSUE TITLE
Calculate cost savings for all cost-related measures

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openprescribing#986]
Similar to #927 which only relates to low-priority measures, should we / can we calculate cost savings for all cost-related measures?

**Comment by HelenCEBM** [comment]
Re. new NHS England pages it will be very useful to implement this @evansd @sebbacon

**Comment by evansd** [comment]
This turns out to not be straightforward as LP measures are defined in a different way from our other cost saving measures.

Our standard measure is: out of all your prescribing on this range of BNF codes, what proportion is of this subset of naughty BNF codes? And our standard cost saving calculation is: how much less would you have spent if your cost-per-item on that prescribing matched that of the best decile?

For LP measures we calculate cost of prescribing per 1000 patients. And for cost saving, we want to calculate the difference if your cost-per-patient matched that of the best decile.

This obviously can be done, but will require a significant refactoring in how the measures are calculated.

As a temporary solution, we are going to try to calculate the saving in JS on the client side for LP measures.

**Comment by brianmackenna** [comment]
User feedback: can we have actual spends for LPP?

This is could be linked to #154 as well. 

Could we rewrite "performance" paragraph and incorporate #154 

> Performance:  This CCG has spent £xxx on this item in the last six months. If it had prescribed in line with the median, this CCG would have spent £2,127 less over the past 6 months. If it had prescribed in line with the best 10%, it would have spent £10,176 less. Two practices (see list) are responsible for 50% of the spend while eight are responsible for 80% of spend (see list)

In this case CCG is parent and practice is child but we should make it work for all dashboards if possible. e.g. Region = parent and STP = Child
